# -*- coding: utf-8 -*-

# EMC is using a database to store all needed information about aircraft, operators, keywords, 
# instruments and so on. Use this program to generate the database


import sqlite3 as lite
import os


aircraft_informations = (
	("AWI - POLAR 5", "Basler Turbo Conversions", "BT-67", "Alfred Wegener Institute (AWI)", "Germa"
     + "ny", "C-GAWI", "POLAR5-AWI.png", "Alfred Wegener Institute"),
	("CNR - ERA Skyarrow", "3I / Magnaghi Aeronautica", "Sky Arrow 650", "Consiglio Nazionale delle"
     + " Ricerche (CNR) - ISAFoM", "Italy", "I-AMMO", "ERA-ISAFM.png", "CNR, Istituto per i Sistemi"
     + " Agricoli e Forestali del Mediterraneo"),
	("CNR - Partenavia", "Partenavia / Vulcanair", "P-68", "Consiglio Nazionale delle Ricerche (CNR"
     + ") - IMAA", "Italy", "I-ALTM", "PARTENAVIA-CNR.png", "CNR, Istituto di Metodologie per l'Ana"
     + "lisi Ambientale"),
	("DLR - C 208", "Cessna Aircraft Company", "Cessna 208", "Deutsches Zentrum fur Luft- und Raumf"
     + "ahrt (DLR)", "Germany", "D-FDLR", "C208-DLR.png", "DLR, CC-BY 3.0"),
	("DLR - DO 228 D-CFFU", "Dornier Flugzeugwerke", "DO-228", "Deutsches Zentrum fur Luft- und Rau"
     + "mfahrt (DLR)", "Germany", "D-CFFU", "DO228-DLR-1.png", "DLR, CC-BY 3.0"),
	("DLR - DO 228 D-CODE", "Dornier Flugzeugwerke", "DO-228", "Deutsches Zentrum fur Luft- und"
     + " Raumfahrt (DLR)", "Germany", "D-CODE", "DLR - DO228-2.png", "DLR, CC-BY 3.0"),
	("DLR - Falcon 20", "Dassault Aviation", "Mystere/Falcon 20", "Deutsches Zentrum fur Luft- und "
     + "Raumfahrt (DLR)", "Germany", "D-CMET", "FALCON20-DLR.png", "DLR, CC-BY 3.0"),
	("Make a choice...", " ", " ", " ", " ", " ", "logo_eufar_emc.png", " "),
	("ENVISCOPE - Learjet 35", "Learjet Aircraft Company", "Learjet 35", "ENVISCOPE", "Germany", "D"
     + "-CGFD", "LEARJET25-ENVISCOPE-3.png", "ENVISCOPE GmbH"),
	("ENVISCOPE - Partenavia", "Partenavia / Vulcanair", "P-68", "ENVISCOPE", "Germany", "D-GERY", 
     "PARTENAVIA68-ENVISCOPE-2.png", "ENVISCOPE GmbH"),
	("FAAM - BAe 146", "BAE Systems", "BAe-146", "Facility for Airborne Atmospheric Measurements (F"
     + "AAM)", "United Kingdom", "G-LUXE", "BAE146-FAAM.png", "NERC, Facility for Airborne Atmosphe"
     + "ric Measurements"),
	("FUB - C 207", "Cessna Aircraft Company", "Cessna 207", "Freie Universitat Berlin (FUB) - ISS",
      "Germany", "D-EAFU", "C207-FUB.png", "Institut fur Weltraumwissenschaften"),
	("INTA - CASA 212 AR", "Construcciones Aeronauticas S.A.", "CASA-212", "Instituto Nacional de T"
     + "ecnica Aeroespacial (INTA)", "Spain", "EC-DTV", "CASA212-INTA.png", "Instituto Nacional de "
     + "Tecnica Aeroespacial"),
	("INTA - CASA 212 RS", "Construcciones Aeronauticas S.A.", "CASA-212", "Instituto Nacional de T"
	 + "ecnica Aeroespacial (INTA)", "Spain", "EC-DUQ", "CASA212-INTA.png", "Instituto Nacional de "
     + "Tecnica Aeroespacial"),
	("KIT - Enduro", "Ultraleichtflug Schmidtler", "Enduro", "Karlsruhe Institute of Technology (KI"
     + "T) - IMK-IFU", "Germany", "D-MIFU", "ENDURO-KIT.png","KIT, Institute of Meteorology and Cli"
     + "mate Research"),
	("NERC - DO 228", "Dornier Flugzeugwerke", "DO-228", "Natural Environment Research Council (NER"
     + "C) - ARSF", "United Kingdom", "EC-DUQ", "DO228-NERC.png", "NERC, Airborne Research and Surv"
     + "ey Facility"),
	("NERC - Twin Otter", "De Havilland Canada", "DHC-6", "Natural Environment Research Council (NE"
     + "RC) - BAS", "United Kingdom", "VP-FAZ", "TWINOTTER-NERC.png", "NERC, British Antarctic Survey"),
	("SAFIRE - ATR 42", "ATR", "ATR-42", "SAFIRE", "France", "F-HMTO", "ATR42-SAFIRE.png", "SAFIRE"),
	("SAFIRE - Falcon 20", "Dassault Aviation", "Mystere/Falcon 20", "SAFIRE", "France", "F-GBTM", 
     "FALCON20-SAFIRE-3.png", "Collection Saspozatlse"),
	("SAFIRE - PIPER Aztec", "Piper Aircraft", "PA23", "SAFIRE", "France", "F-BLEB", "PIPERAZTEC-SA"
     + "FIRE.png", "SAFIRE"),
	("UEDIN - ECO Dimona", "Diamond Aircraft Industries", "HK36TTC ECO Dimona", "The University of "
     + "Edinburgh (UEDIN) - IAES", "United Kingdom", "G-GEOS", "DIAMOND-UEDIN-1.png", "UEDIN, Airbo"
     + "rne GeoSciences"),
	)


topic_dict = (
	("Biota","biota"),
	("Boundaries","boundaries"),
	("Climatology / Meteorology / Atmosphere","climatologyMeteorologyAtmosphere"),
	("Economy","economy"),
	("Elevation","elevation"),
	("Environment","environment"),
	("Farming","farming"),
	("Geoscientific Information","geoscientificInformation"),
	("Health","health"),
	("Imagery / Base Maps / Earth Cover","imageryBaseMapsEarthCover"),
	("Intelligence / Military","intelligenceMilitary"),
	("Inland Waters","inlandWaters"),
	("Location","location"),
	("Oceans","oceans"),
	("Planning / Cadastre","planningCadastre"),
	("Society","society"),
	("Structure","structure"),
	("Transportation","transportation"),
	("Utilities / Communication","utilitiesCommunication")
	)


language_role_dict = (
	('Bulgarian','bul'),
	('Czech','ces'),
	('Danish','dan'),
	('Dutch','dut'),
	('English','eng'),
	('Estonian','est'),
	('Finnish','fin'),
	('French','fre'),
	('German','ger'),
	('Greek','gre'),
	('Hungarian','hun'),
	('Irish','gle'),
	('Italian','ita'),
	('Latvian','lav'),
	('Lithuanian','lit'),
	('Maltese','mlt'),
	('Polish','pol'),
	('Portuguese','por'),
	('Romanian','rum'),
	('Slovak','slo'),
	('Slovenian', 'slv'),
	('Spanish','spa'),
	('Swedish','swe'),
	('Author','author'),
	('Custodian','custodian'),
	('Distributor','distributor'),
	('Originator','originator'),
	('Owner','owner'),
	('Point of Contact','pointOfContact'),
	('Principal Investigator','principalInvestigator'),
	('Processor','processor'),
	('Publisher','publisher'),
	('Resource Provider','resourceProvider'),
	('User','user'),
	('Alfred Wegener Institute (AWI)','AWI'),
	('Consiglio Nazionale delle Ricerche (CNR) - ISAFoM','CNR-ISAFoM'),
	('Consiglio Nazionale delle Ricerche (CNR) - IMAA','CNR-IMAA'),
	('Deutsches Zentrum fur Luft- und Raumfahrt (DLR)','DLR'),
	('ENVISCOPE','Enviscope'),
	('Facility for Airborne Atmospheric Measurements (FAAM)','FAAM'),
	('Freie Universitat Berlin (FUB) - ISS','FUB-ISS'),
	('Instituto Nacional de Tecnica Aeroespacial (INTA)','INTA'),
	('Karlsruhe Institute of Technology (KIT) - IMK-IFU','KIT-IMK-IFU'),
	('Natural Environment Research Council (NERC) - ARSF','NERC-ARSF'),
	('Natural Environment Research Council (NERC) - BAS','NERC-BAS'),
	('SAFIRE','SAFIRE'),
	('The University of Edinburgh (UEDIN) - IAES','UEDIN-IAES')
	)


unit_dict = (
    ('Centimetre(s)', 'cm'),
    ('Decimal degree(s)', 'dd'),
    ('Kilometre(s)', 'km'),
    ('Metre(s)', 'm'),
    )


ceos_science_keywords = [
	["Agriculture","Agricultural aquatic sciences",""],
	["Agriculture","Agricultural chemicals",""],
	["Agriculture","Agricultural engineering","kw_agriEngineering_ck"],
	["Agriculture","Agricultural plant science","kw_agriPlant_ck"],
	["Agriculture","Animal commodities",""],
	["Agriculture","Animal science",""],
	["Agriculture","Feed products",""],
	["Agriculture","Food science","kw_foodScience_ck"],
	["Agriculture","Forest science","kw_forestScience_ck"],
	["Agriculture","Plant commodities",""],
	["Agriculture","Soils","kw_soils_ck"],
	["Atmosphere","Aerosols","kw_aerosols_ck"],
	["Atmosphere","Air quality","kw_airQuality_ck"],
	["Atmosphere","Altitude","kw_altitude_ck"],
	["Atmosphere","Atmospheric chemistry","kw_atmChemistry_ck"],
	["Atmosphere","Atmospheric electricity","kw_atmElectricity_ck"],
	["Atmosphere","Atmospheric phenomena","kw_atmPhenomena_ck"],
	["Atmosphere","Atmospheric pressure","kw_atmPressure_ck"],
	["Atmosphere","Atmospheric radiation","kw_atmRadiation_ck"],
	["Atmosphere","Atmospheric temperature","kw_atmTemperature_ck"],
	["Atmosphere","Atmospheric water vapor","kw_atmVapor_ck"],
	["Atmosphere","Atmospheric winds","kw_atmWinds_ck"],
	["Atmosphere","Clouds","kw_clouds_ck"],
	["Atmosphere","Precipitation","kw_precipitation_ck"],
	["Biosphere","Aquatic ecosystems",""],
	["Biosphere","Ecological dynamics","kw_ecoDynamics_ck"],
	["Biosphere","Terrestrial ecosystems","kw_terEcosystems_ck"],
	["Biosphere","Vegetation","kw_vegetation_ck"],
	["Cryosphere","Frozen ground","kw_frozenGround_ck"],
	["Cryosphere","Glaciers / Ice sheet","kw_glaciersIcesheet_ck"],
	["Cryosphere","Sea ice","kw_seaIce_ck"],
	["Cryosphere","Snow / Ice","kw_snowIce_ck"],
	["Land Surface","Erosion / Sedimentation","kw_erosionSedimentation_ck"],
	["Land Surface","Frozen ground",""],
	["Land Surface","Geomorphology","kw_geomorphology_ck"],
	["Land Surface","Land temperature","kw_landTemperature_ck"],
	["Land Surface","Land use / Land cover","kw_landCover_ck"],
	["Land Surface","Landscape","kw_landscape_ck"],
	["Land Surface","Soils",""],
	["Land Surface","Surface radiative properties","kw_surfaceProperties_ck"],
	["Land Surface","Topography","kw_topography_ck"],
	["Ocean","Aquatic sciences",""],
	["Ocean","Bathymetry / Seafloor topography","kw_bathymetry_ck"],
	["Ocean","Coastal processes","kw_coastalProcesses_ck"],
	["Ocean","Marine environment","kw_marineEnvironment_ck"],
	["Ocean","Marine geophysics","kw_marineGeophysics_ck"],
	["Ocean","Marine sediments",""],
	["Ocean","Marine volcanisme",""],
	["Ocean","Ocean acoustics",""],
	["Ocean","Ocean chemistry",""],
	["Ocean","Ocean circulation",""],
	["Ocean","Ocean heat budget",""],
	["Ocean","Ocean optics",""],
	["Ocean","Ocean pressure",""],
	["Ocean","Ocean temperature",""],
	["Ocean","Ocean waves","kw_oceanWaves_ck"],
	["Ocean","Ocean winds","kw_oceanWinds_ck"],
	["Ocean","Salinity / Density",""],
	["Ocean","Sea ice",""],
	["Ocean","Sea surface topography","kw_seaTopography_ck"],
	["Ocean","Tides","kw_seaTides_ck"],
	["Ocean","Water quality","kw_waterQuality_ck_2"],
	["Solid Earth","Earth gases / liquides",""],
	["Solid Earth","Geochemistry",""],
	["Solid Earth","Geodetics","kw_geodetics_ck"],
	["Solid Earth","Geomagnetism","kw_geomagnetism_ck"],
	["Solid Earth","Geomorphic landforms / processes","kw_geomorphicLandforms_ck"],
	["Solid Earth","Geothermal Dynamics",""],
	["Solid Earth","Gravity / gravitational field","kw_gravity_ck"],
	["Solid Earth","Rocks / Minerals / Crystals",""],
	["Solid Earth","Tectonics",""],
	["Spectral / Engineering","Gamma ray","kw_gammaRay_ck"],
	["Spectral / Engineering","Infrared wavelengths","kw_irWavelengths_ck"],
	["Spectral / Engineering","LIDAR","kw_lidar_ck"],
	["Spectral / Engineering","Microwave","kw_microwave_ck"],
	["Spectral / Engineering","Platform characteristics",""],
	["Spectral / Engineering","RADAR","kw_radar_ck"],
	["Spectral / Engineering","Radio wave","kw_radioWave_ck"],
	["Spectral / Engineering","Sensor characteristics",""],
	["Spectral / Engineering","Ultraviolet wavelengths","kw_uvWavelentghs_ck"],
	["Spectral / Engineering","Visible wavelengths","kw_visWavelentghs_ck"],
	["Spectral / Engineering","X-ray","kw_xRay_ck"],
	["Sun-Earth Interactions","Ionosphere / Magnetosphere dynamics","kw_ionosMagnetos_ck"],
	["Sun-Earth Interactions","Solar activity","kw_solarActivity_ck"],
	["Sun-Earth Interactions","Solar energetic particle","kw_solarFlux_ck"],
	["Sun-Earth Interactions","Solar energetic particle properties","kw_solarFlux_ck"],
	["Terrestrial Hydrosphere","Glaciers / Ice sheets",""],
	["Terrestrial Hydrosphere","Ground water","kw_groundWater_ck"],
	["Terrestrial Hydrosphere","Snow / Ice",""],
	["Terrestrial Hydrosphere","Surface water","kw_surfaceWater_ck"],
	["Terrestrial Hydrosphere","Water quality / chemistry","kw_waterQuality_ck"],
	]

emc_locations = [
	["Make a choice ...",""],
	["Continents","Africa"],
	["Continents","Antarctica"],
	["Continents","Asia"],
	["Continents","Oceania"],
	["Continents","Europe"],
	["Continents","North America"],
	["Continents","South America"],
	["Countries","Afghanistan"],
	["Countries","Albania"],
	["Countries","Algeria"],
	["Countries","Amazonia"],
	["Countries","American Samoa"],
	["Countries","Amsterdam And St. Paul Islands"],
	["Countries","Andaman Islands"],
	["Countries","Andorra"],
	["Countries","Angola"],
	["Countries","Anguilla"],
	["Countries","Antigua And Barbuda"],
	["Countries","Argentina"],
	["Countries","Armenia"],
	["Countries","Aruba"],
	["Countries","Ascension Island"],
	["Countries","Australia"],
	["Countries","Austria"],
	["Countries","Azerbaijan"],
	["Countries","Bahamas"],
	["Countries","Bahrain"],
	["Countries","Baker Island"],
	["Countries","Bangladesh"],
	["Countries","Barbados"],
	["Countries","Belarus"],
	["Countries","Belgium"],
	["Countries","Belize"],
	["Countries","Benin"],
	["Countries","Bhutan"],
	["Countries","Bolivia"],
	["Countries","Bonaire"],
	["Countries","Bosnia And Herzegovina"],
	["Countries","Botswana"],
	["Countries","Bouvet Island"],
	["Countries","Brazil"],
	["Countries","British Isles"],
	["Countries","Brunei"],
	["Countries","Bulgaria"],
	["Countries","Burkina Faso"],
	["Countries","Burma"],
	["Countries","Burundi"],
	["Countries","Cambodia"],
	["Countries","Cameroon"],
	["Countries","Canada"],
	["Countries","Caribbean"],
	["Countries","Cayman Islands"],
	["Countries","Central African Republic"],
	["Countries","Ceuta"],
	["Countries","Chad"],
	["Countries","Channel Islands"],
	["Countries","Chile"],
	["Countries","China"],
	["Countries","Christmas Island"],
	["Countries","Cocos Islands"],
	["Countries","Colombia"],
	["Countries","Comoros"],
	["Countries","Congo, Democratic Republic"],
	["Countries","Congo, Republic"],
	["Countries","Cook Islands"],
	["Countries","Corsica"],
	["Countries","Costa Rica"],
	["Countries","Cote D'ivoire"],
	["Countries","Croatia"],
	["Countries","Crozet Islands"],
	["Countries","Cuba"],
	["Countries","Curacao"],
	["Countries","Cyprus"],
	["Countries","Czech Republic"],
	["Countries","Denmark"],
	["Countries","Dhekelia"],
	["Countries","Djibouti"],
	["Countries","Dominica"],
	["Countries","Dominican Republic"],
	["Countries","Ecuador"],
	["Countries","Egypt"],
	["Countries","El Salvador"],
	["Countries","Equatorial Guinea"],
	["Countries","Eritrea"],
	["Countries","Estonia"],
	["Countries","Ethiopia"],
	["Countries","Faeroe Islands"],
	["Countries","Falkland Islands"],
	["Countries","Fiji"],
	["Countries","Finland"],
	["Countries","France"],
	["Countries","French Guiana"],
	["Countries","French Polynesia"],
	["Countries","Gabon"],
	["Countries","Galapagos Islands"],
	["Countries","Gambia"],
	["Countries","Gaza Strip"],
	["Countries","Georgia, Republic"],
	["Countries","Germany"],
	["Countries","Ghana"],
	["Countries","Gibraltar"],
	["Countries","Gough Island"],
	["Countries","Greece"],
	["Countries","Greenland"],
	["Countries","Grenada"],
	["Countries","Guadeloupe"],
	["Countries","Guam"],
	["Countries","Guatemala"],
	["Countries","Guinea"],
	["Countries","Guinea-Bissau"],
	["Countries","Guyana"],
	["Countries","Haiti"],
	["Countries","Hawaii Island"],
	["Countries","Hawaiian Islands"],
	["Countries","Honduras"],
	["Countries","Hong Kong"],
	["Countries","Howland Island"],
	["Countries","Hungary"],
	["Countries","Iceland"],
	["Countries","India"],
	["Countries","Indonesia"],
	["Countries","Iran"],
	["Countries","Iraq"],
	["Countries","Ireland"],
	["Countries","Israel"],
	["Countries","Italy"],
	["Countries","Jamaica"],
	["Countries","Japan"],
	["Countries","Jarvis Island"],
	["Countries","Johnston Atoll"],
	["Countries","Jordan"],
	["Countries","Kahoolawe"],
	["Countries","Kauai"],
	["Countries","Kazakhstan"],
	["Countries","Kenya"],
	["Countries","Kerguelen Islands"],
	["Countries","Kingman Reef"],
	["Countries","Kiribati"],
	["Countries","Kosovo"],
	["Countries","Kuwait"],
	["Countries","Kyrgyzstan"],
	["Countries","Laeso"],
	["Countries","Lake Chad"],
	["Countries","Lake Malawi"],
	["Countries","Lake Tanganyika"],
	["Countries","Lake Victoria"],
	["Countries","Lanai"],
	["Countries","Laos"],
	["Countries","Latvia"],
	["Countries","Lebanon"],
	["Countries","Lesotho"],
	["Countries","Liberia"],
	["Countries","Libya"],
	["Countries","Liechtenstein"],
	["Countries","Lithuania"],
	["Countries","Luxembourg"],
	["Countries","Macau"],
	["Countries","Macedonia"],
	["Countries","Madagascar"],
	["Countries","Madeira"],
	["Countries","Malawi"],
	["Countries","Malaysia"],
	["Countries","Maldives"],
	["Countries","Mali"],
	["Countries","Malta"],
	["Countries","Marshall Islands"],
	["Countries","Martinique"],
	["Countries","Maui"],
	["Countries","Mauritania"],
	["Countries","Mauritius"],
	["Countries","Melanesia"],
	["Countries","Mexico"],
	["Countries","Micronesia"],
	["Countries","Midway Atoll"],
	["Countries","Moldova"],
	["Countries","Molokai"],
	["Countries","Monaco"],
	["Countries","Mongolia"],
	["Countries","Montenegro"],
	["Countries","Montserrat"],
	["Countries","Morocco"],
	["Countries","Mozambique"],
	["Countries","Namibia"],
	["Countries","Nauru"],
	["Countries","Navassa Island"],
	["Countries","Nepal"],
	["Countries","Netherlands Antilles"],
	["Countries","Netherlands"],
	["Countries","New Caledonia"],
	["Countries","New Zealand"],
	["Countries","Nicaragua"],
	["Countries","Nicobar Islands"],
	["Countries","Niger"],
	["Countries","Nigeria"],
	["Countries","Niihau"],
	["Countries","Niue"],
	["Countries","Norfolk Island"],
	["Countries","North Korea"],
	["Countries","Northern Mariana Islands"],
	["Countries","Norway"],
	["Countries","Oahu"],
	["Countries","Okinawa"],
	["Countries","Oman"],
	["Countries","Pakistan"],
	["Countries","Palau"],
	["Countries","Palestine"],
	["Countries","Palmyra Atoll"],
	["Countries","Panama"],
	["Countries","Papua New Guinea"],
	["Countries","Paraguay"],
	["Countries","Peru"],
	["Countries","Philippines"],
	["Countries","Pitcairn Island"],
	["Countries","Pitcairn Islands"],
	["Countries","Poland"],
	["Countries","Polynesia"],
	["Countries","Portugal"],
	["Countries","Puerto Rico"],
	["Countries","Qatar"],
	["Countries","Red Sea"],
	["Countries","Reunion"],
	["Countries","Romania"],
	["Countries","Russia"],
	["Countries","Rwanda"],
	["Countries","Saba"],
	["Countries","Sable Island"],
	["Countries","Samoa"],
	["Countries","San Marino"],
	["Countries","Sao Tome And Principe"],
	["Countries","Sardinia"],
	["Countries","Saudi Arabia"],
	["Countries","Scandinavia"],
	["Countries","Senegal"],
	["Countries","Serbia"],
	["Countries","Seychelles"],
	["Countries","Sicily"],
	["Countries","Sierra Leone"],
	["Countries","Singapore"],
	["Countries","Slovakia"],
	["Countries","Slovenia"],
	["Countries","Solomon Islands"],
	["Countries","Somalia"],
	["Countries","South Africa"],
	["Countries","South Georgia Island"],
	["Countries","South Korea"],
	["Countries","South Orkney Islands"],
	["Countries","South Sandwich Islands"],
	["Countries","Spain"],
	["Countries","Spratly Islands"],
	["Countries","Sri Lanka"],
	["Countries","St Barthelemy"],
	["Countries","St Eustatius"],
	["Countries","St Helena"],
	["Countries","St Kitts And Nevis"],
	["Countries","St Lucia"],
	["Countries","St Maarten"],
	["Countries","St Martin"],
	["Countries","St Pierre And Miquelon"],
	["Countries","St Vincent And The Grenadines"],
	["Countries","Sudan"],
	["Countries","Suriname"],
	["Countries","Svalbard And Jan Mayen"],
	["Countries","Swaziland"],
	["Countries","Sweden"],
	["Countries","Switzerland"],
	["Countries","Syria"],
	["Countries","Taiwan"],
	["Countries","Tajikistan"],
	["Countries","Tanzania"],
	["Countries","Thailand"],
	["Countries","Togo"],
	["Countries","Tokelau"],
	["Countries","Tonga"],
	["Countries","Trinidad And Tobago"],
	["Countries","Tristan Da Cunha"],
	["Countries","Tunisia"],
	["Countries","Turkey"],
	["Countries","Turkmenistan"],
	["Countries","Turks And Caicos Islands"],
	["Countries","Tuvalu"],
	["Countries","Uganda"],
	["Countries","Ukraine"],
	["Countries","United Arab Emirates"],
	["Countries","United Kingdom"],
	["Countries","United States of America"],
	["Countries","Uruguay"],
	["Countries","Uzbekistan"],
	["Countries","Vanuatu"],
	["Countries","Vatican City"],
	["Countries","Venezuela"],
	["Countries","Vietnam"],
	["Countries","Virgin Islands"],
	["Countries","Wake Island"],
	["Countries","Wallis And Futuna Islands"],
	["Countries","Yemen"],
	["Countries","Zambia"],
	["Countries","Zanzibar"],
	["Countries","Zimbabwe"],
	["Oceans","Atlantic Ocean"],
	["Oceans","Arctic Ocean"],
	["Oceans","Indian Ocean"],
	["Oceans","Pacific Ocean"],
	["Oceans","Southern Ocean"],
	["Regions","Arctic Region"],
	["Regions","Atlantic Ocean Islands"],
	["Regions","Central Africa"],
	["Regions","Central America"],
	["Regions","Central Europe"],
	["Regions","Eastern Africa"],
	["Regions","Eastern Asia"],
	["Regions","Eastern Europe"],
	["Regions","Indian Ocean Islands"],
	["Regions","Middle East"],
	["Regions","North America"],
	["Regions","Northern Africa"],
	["Regions","Northern Europe"],
	["Regions","Pacific Islands"],
	["Regions","South America"],
	["Regions","Southcentral Asia"],
	["Regions","Southern Asia"],
	["Regions","Southern Europe"],
	["Regions","Western Africa"],
	["Regions","Western Asia"],
	["Regions","Western Europe"],
	]


window_messages = (
	("infoButton_1","<p>Available in the EUFAR TA application form (<b>Project title</b>), this i"
     + "s a characteristic and often unique name identifying the resource.</p><p><u>Example:</u> Our"
     + " Small Project.</p>"),
	("infoButton_2","<p>This is a brief narrative summary of the content of the resource. It is ava"
     + "ilable in the EUFAR TA application form (<b>Scientific problems being addressed by the expe"
     + "riments to be performed</b>).</p><p><u>Example:</u> SMALLPROJECT is a small project. Its go"
     + "al is to explain what to do and what to write.</p>"),
	("infoButton_3","<p>This is the type of resource being described by the metadata, and can be ei"
     + "ther dataset or series.</p><p><u>Example:</u> Dataset.</p>"),
	("infoButton_4","<p>The resource locator defines the link(s) to the resource and/or the link to"
     + " additional information about the resource. For EUFAR projects, it is automatically filled "
     + "in with the link to the EUFAR database.</p><p><u>Example:</u> http://browse.ceda.ac.uk/brow"
     + "se/badc/eu far/docs/00eufararchive contents.html</p>"),
	("infoButton_5","<p hyphens='auto'>This element uniquely identifying the project and it is gene"
     + "rally formed with mandatory and/or optional string codes. In a EUFAR project, it is availab"
     + "le in the EUFAR TA application form (<b>Project acronym</b>).</p><p><u>Example:</u> SMALLPR"
     + "OJECT"),
	("infoButton_6","<p>The language(s) used within the resource. In a EUFAR project, English is al"
     + "ways selected and should not be changed. </p><p><u>Example:</u> English.</p>"),
	("infoButton_7","<p>The topic category is a high-level classification scheme to facilitate the "
     + "grouping and topic-based search of available spatial data resources. This item corresponds "
     + "to the Main <b>Scientific Field / specific discipline</b> in the EUFAR Ta application form."
     + "</p><p><u>Example:</u> Environment.</p>"),
	("infoButton_8","<p>The keyword value is a commonly used word to describe the subject. The keyw"
     + "ord scheme is from NASA/Global Change Master Directory (GCMD) Earth Science Keywords.</p><p"
     + "><u>Example:</u> Forest science, Aerosols, Clouds.</p>"),
	("infoButton_9","<p>The selection of an aircraft can help to improve storage and queries in a d"
     + "atabase. Please select here the aircraft used to acquire and prepare the actual data and me"
     + "tadata, and click on the '+' button to add it to the list. It's possible to add multiple ai"
     + "rcraft.<p><u>Example:</u> AWI - POLAR 5.</p>"),
    ("infoButton_10","<p>The selection of an instrument, or multiple instruments, can help to impro"
     + "ve storage and queries in a database. Please select here the instrument(s) used to acquire "
     + "and prepare the actual data and metadata, and click on the '+' icon to add it into the list"
     + ".</p><p><u>Example:</u> APEX.</p>"),
    ("infoButton_11","<p>This is the name of the formal location covered by the dataset. It is avai"
     + "lable in the EUFAR TA application form.</p><p><u>Example:</u> Countries / France.</p>"),
    ("infoButton_12","<p>This is the extent of the resource in the geographic space, given as a bou"
     + "nding box. The bounding box shall be expressed with westbound and eastbound longitudes in d"
     + "ecimal degree (-180.00 to 180.00) and southbound and northbound latitudes in decimal degree"
     + " (-90.00 to 90.00), with a precision of two decimals.</p><p><u>Example:</u> for a bounding "
     + "box above United Kingdom (58.65°N / -11.80°W and 50.69°N / 2.32°E)</p><p align='center'>58."
     + "65</p><p align='center'>-11.80 &nbsp;&nbsp;&nbsp;&nbsp; 2.32</p><p align='center'>50.69</p>"),
    ("infoButton_13","<p>Each spatial resolution is either an equivalent scale OR a ground sample d"
     + "istance. When two equivalent scales or two ground sample distances are expressed, the spati"
     + "al resolution is an interval bounded by these two values. It is only mandatory if an equiva"
     + "lent scale or a resolution distance can be specified.</p><p><u>Example:</u> a dataset with "
     + "a spatial resolution of 0.25°x0.25° -> 0.25 / Decimal degree (dd).</p>"),
    ("infoButton_14","<p>This is the date of publication of the resource. In a EUFAR project, the d"
     + "ate of entry into EUFAR database (N8-DB) should be used and set <b>before</b> the current d"
     + "ate.</p><p><u>Example:</u> 2015/07/12.</p>"),
    ("infoButton_15","<p>This is the date of last revision of the resource if available. In a EUFAR"
     + " project, it is automatically created by the EUFAR database (date stamp).</p>"),
    ("infoButton_16","<p>This is the date of creation of the resource. In a EUFAR project, the date"
     + " should be set to the date of data processing.</p><p><u>Example:</u> 2015/07/11.</p>"),
    ("infoButton_17","<p>The temporal extent defines the time period covered by the data acquisitio"
     + "n. It can be composed of multiple phases if necessary.</p><p><u>Example:</u></p>&nbsp;&nbsp"
     + ";&nbsp;&nbsp; 2015/07/01 - 2015/07/03<br> &nbsp;&nbsp;&nbsp;&nbsp; 2015/07/05 - 2015/07/07<"
     + "/p>"),
    ("infoButton_18","<p>This metadata element defines the conditions for access and use of spatial"
     + " data sets. In a EUFAR project, this element has already been filled in in agreement with t"
     + "he EUFAR Consortium Agreement.</p>"),
    ("infoButton_19","<p>This metadata element defines the limitations for public access to spatial"
     + " data sets and the reason for that. In a EUFAR project, this element has already been fille"
     + "d in in agreement with the EUFAR Consortium Agreement.</p>"),
    ("infoButton_20","<p>This is the description of the organisation responsible for the production"
     + " of the resource. The description shall include the name of the organisation.</p><p><u>Exam"
     + "ple:</u> SAFIRE</p>"),
    ("infoButton_21","<p>This is the email of the point of contact.</p><p><u>Example:</u> john.doe@"
     + "email.com.</p>"),
    ("infoButton_22","<p>This is the role of the responsible organisation. In a EUFAR project, the "
     + "value is <b>Point of Contact</b>.</p><p><u>Example:</u> Point of Contact.</p>"),
    ("infoButton_23","<p>The date which specifies when the metadata record was created or updated.<"
     + "/p><p><u>Example:</u> 2015/07/14.</p>"),
    ("infoButton_24","<p>This is the language in which the metadata elements are expressed. In a EU"
     + "FAR project, English is always selected and should not be changed.</p><p><u>Example:</u> En"
     + "glish.</p>"),
    ("infoButton_25","<p>This is the name and the contact e-mail of the party responsible for the m"
     + "etadata.</p><p><u>Example:</u> SAFIRE or John Doe</p>"),
    ("infoButton_26","<p>This is a statement on process history and/or overall quality of the spati"
     + "al data set. The user has to fill in the requested fields. Once it has been done, EMC will "
     + "format the inputs as free text to conform to INSPIRE standard.</p>"),
    ("infoButton_27","<p>Those items are a link to the description of all procedures, constants and"
     + " materials applied to raw digital data for calibration purpose. A free text description is "
     + "also accepted for each item if necessary.</p><p><u>Example:</u> <b>http://www.operator.com/"
     + "path/pa th2/document_to_explain_procedures.html</b> or <b>We proceed this way and this way "
     + "to calibrate the instrument / The calibration constants come from this book and this public"
     + "ation</b>.</p>"),
    ("infoButton_28","<p>Once the data has been processed, the final output format. Multiple entrie"
     + "s are possible. If 'Other' is selected for free text, the characters ';', '|' and '/' are p"
     + "rohibited.</p><p><u>Example:</u> NetCDF.</p>"),
    ("infoButton_29","<p>The Quality and Validity section needs a brief description, or a link to t"
     + "he document, of the operator's standard procedures explaining the quality-control flagging "
     + "applied to individual data points.</p><p><u>Example:</u> <b>http://www.operator.com/path/p "
     + "ath2/document_to_explain_flagging.html</b> or <b>Each point has a certain number of flag to"
     + " say if the measurement is allright or not</b>.</p>"),
    ("infoButton_30","<p>What are the empirical assumptions, made when processing the data ? Please"
     + " give references if possible.</p><p><u>Example:</u> aerosol refractive index, ice crystal b"
     + "ulk density.</p>"),
    ("infoButton_31","<p>In case of issues with the sensor calibration, it is important to track ba"
     + "ck the calibration cycle.</p>"),
    ("infoButton_32","<p>The setting up of the spectral mode can be changed with some sensor system"
     + "s.</p>"),
    ("infoButton_33","<p>As basic processing information, it is important to know if the DC was alr"
     + "eady corrected, or if this has to be done before all subsequent information retrieval.</p>"),
    ("infoButton_34","<p>Some data Quality Indicators can be assigned to single pixels and can ther"
     + "efore provided as Quality Layers in a spatial dataset.</p>"),
    ("infoButton_35","<p>This mask includes all pixels for which corrections where carried out in o"
     + "ne or more bands.</p>"),
    ("infoButton_36","<p>All pixels where defects were detected, but which were not corrected, are "
     + "included in this bad pixel mask.</p>"),
    ("infoButton_37","<p>Saturation occurs when the sensed and amplified signal exceeds the dynamic"
     + " range of the detector.</p>"),
    ("infoButton_38","<p>The quality of pixels, spatially or spectrally neighbouring a saturated pi"
     + "xel, can be reduced for sensor designs based on frame-transfer CCDs (e.g., AISA Eagle). Thu"
     + "s these pixels are detected and included in a separate mask.</p>"),
    ("infoButton_39","<p>Position information might include data gaps, errors and increased uncerta"
     + "inties related to the reception of a small number of GPS satellites, or rapid changes in ca"
     + "se of turbulent flight conditions. When geocoding, the corresponding scan lines might have "
     + "an error or an increased uncertainty in geo-location.</p>"),
    ("infoButton_40","<p>In certain cases, the parameters required for an accurate atmospheric corr"
     + "ection cannot be estimated for all pixels in an image. Such critical pixels should be flagg"
     + "ed.</p>"),
    ("infoButton_41","<p>One of the limiting factors, regarding processing quality, is the accuracy"
     + " and spatial resolution of the DEM. Therefore one can expect an increased uncertainty where"
     + "ver the terrain is rough. Thus the local variability of the terrain height is calculated in"
     + " a <b>moving window</b> approach, and critical areas are detected and flagged in this quali"
     + "ty layer.</p>"),
    ("infoButton_42","<p>In addition to the increased DEM uncertainty in rough terrain, areas with "
     + "high slope values and/or unfavourable local illumination (large solar zenith angles) are li"
     + "kely affected by an increased uncertainty for the terrain correction.</p>"),
    ("infoButton_43","<p>Regarding the strength of the BRDF effect and the related accuracy of BRDF"
     + " correction, critical conditions should be addressed. The strength of the BRDF effect is a "
     + "function of viewing / illumination geometry, terrain as well as land cover. Therefore stron"
     + "gly affected areas can be detected based on these parameters and are subsequently flagged.<"
     + "/p>")
    )


'''intruments_information = [
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Aerosol Monitors","AARP","University of Manchester"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Aerosol Monitors","CAPS","Droplet Measurement Technologies"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Aerosol Monitors","CAS Spectrometer","Baumgardner et al., 2001"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Aerosol Monitors","Cloud Imaging Probe","Not specified"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Aerosol Monitors","LASAIR-5295","Particle Measurement Systems"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Aerosol Monitors","PCASP-100X","Droplet Measurement Technologies"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Aerosol Monitors","PCASP-SPP200","Droplet Measurement Technologies"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Aerosol Monitors","SPEC Hawkeye","Stratton Park Engineering Company"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Aerosol Monitors","UHSAS-A","Droplet Measurement Technologies"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Aerosol Monitors","VACC","University of Leeds"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Aethalometers","AE-42","Magee Scientific"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Aethalometers","AE-52 Aethelometer","Magee Scientific"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Aethalometers","PSAP","Radiance Research Inc."],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Carbon Analyzers","AL5002","Aero-Laser Gmbh"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Carbon Analyzers","AL5003","Aero-Laser Gmbh"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Carbon Analyzers","SP-2","Droplet Measurement Technologies"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Carbon, Hydrogen, Nitrogen Analyzers","CW-QCLAS","Aerodyne Research Inc."],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Condensation Nuclei Counter","CCN Counter","Droplet Measurement Technologies"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Condensation Nuclei Counter","COPAS","University of Mainz"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Condensation Nuclei Counter","CPI","Stratton Park Engineering Company"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Condensation Nuclei Counter","SMPS","Grimm Technologies Inc."],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Condensation Nuclei Counter","TSI-3007","TSI Inc."],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Condensation Nuclei Counter","TSI-3010","TSI Inc."],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Condensation Nuclei Counter","TSI-3022","TSI Inc."],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Condensation Nuclei Counter","TSI-3025","TSI Inc."],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Condensation Nuclei Counter","TSI-3776","TSI Inc."],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Condensation Nuclei Counter","TSI-3786","TSI Inc."],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Fluorometers","HALOX","Forschungszentrum Julich GmbH"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Flurorescence Spectroscopy","FAGE","University of Leeds"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Gas Chromatographs","HAGAR","University of Frankfurt"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Gas Chromatographs","PAN GC","Ai Qualitek Ltd"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Gas Chromatographs","VOC GC","Airmotec AG"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Gas Sensors","Formaldehyde Detectors","Others"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Gas Sensors","IR Gas analyzer","Edinburgh Sensors"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Gas Sensors","LGR 907","Los Gatos Research Inc."],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Gas Sensors","LGR DLT100","Los Gatos Research Inc."],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Gas Sensors","LI-COR 6262","LI-COR"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Gas Sensors","LI-COR 7500","LI-COR"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Gas Sensors","ORAC","University of Leeds"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Gas Sensors","PERCA","University of Leceister"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Gas Sensors","Peroxide Detectors","Others"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Nondispersive Infrared Gas Analyzers","S-5002","Sistemas Instalaciones Redes S.A."],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Nondispersive Infrared Gas Analyzers","S-5006","Sistemas Instalaciones Redes S.A."],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Nondispersive Infrared Gas Analyzers","S-5012","Sistemas Instalaciones Redes S.A."],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Ozone Monitors","Ozone Monitor 202","2B Technologies"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Ozone Monitors","Ozone Monitor","2B Technologies"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Ozone Monitors","PSI-O3","Paul Scherrer Institut"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Ozone Monitors","SA 41M","Environment S.A."],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Ozone Monitors","TECO 42C","ThermoScientific"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Ozone Monitors","TECO 42S","ThermoScientific"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Ozone Monitors","TECO 48CS","ThermoScientific"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Ozone Monitors","TECO 49PS","ThermoScientific"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Ozone Monitors","TECO 49S","ThermoScientific"],
	["In Situ/Laboratory Instruments","Current/Wind Meters","Counterflow Virtual Impactors","Counterflow Virtual Impactor","Met Office"],
	["In Situ/Laboratory Instruments","Current/Wind Meters","Wind Monitors","5-hole Turbulence Probe","DLR"],
	["In Situ/Laboratory Instruments","Current/Wind Meters","Wind Monitors","5-hole Turbulence Probe","FAAM"],
	["In Situ/Laboratory Instruments","Current/Wind Meters","Wind Monitors","5-hole Turbulence Probe","MetAir AG"],
	["In Situ/Laboratory Instruments","Current/Wind Meters","Wind Monitors","5-hole Turbulence Probe","SAFIRE"],
	["In Situ/Laboratory Instruments","Current/Wind Meters","Wind Monitors","858AJ28","Rosemount"],
	["In Situ/Laboratory Instruments","Current/Wind Meters","Wind Monitors","AIMMS-20","Aventech Inc."],
	["In Situ/Laboratory Instruments","Current/Wind Meters","Wind Monitors","Aircraft Systems","Others"],
	["In Situ/Laboratory Instruments","Current/Wind Meters","Wind Monitors","BAT","NOAA / Airborne Research Australia"],
	["In Situ/Laboratory Instruments","Current/Wind Meters","Wind Monitors","Mobile Flux Platform","IBIMET CNR"],
	["In Situ/Laboratory Instruments","Current/Wind Meters","Wind Monitors","Others","Others"],
	["In Situ/Laboratory Instruments","Current/Wind Meters","Wind Monitors","Solent HS","Gill Instruments Ltd"],
	["In Situ/Laboratory Instruments","Current/Wind Meters","Wind Monitors","Solent HS-100","Gill Instruments Ltd"],
	["In Situ/Laboratory Instruments","Current/Wind Meters","Wind Monitors","Solent HS-50","Gill Instruments Ltd"],
	["In Situ/Laboratory Instruments","Magnetic/Motion Sensors","Accelerometers","3150","ICSensors / Measurement Specialties"],
	["In Situ/Laboratory Instruments","Magnetic/Motion Sensors","Accelerometers","Aircraft Systems","Others"],
	["In Situ/Laboratory Instruments","Magnetic/Motion Sensors","Accelerometers","Kistler 3 axes accelerometers","Kistler Instrumente AG"],
	["In Situ/Laboratory Instruments","Magnetic/Motion Sensors","Accelerometers","Others","Others"],
	["In Situ/Laboratory Instruments","Magnetic/Motion Sensors","Accelerometers","SFIM 3 axes accelerometers","SFIM"],
	["In Situ/Laboratory Instruments","Magnetic/Motion Sensors","Accelerometers","Sundstrand 3 axes accelerometers","Sundstrand"],
	["In Situ/Laboratory Instruments","Magnetic/Motion Sensors","Gravimeters","S56","Micro-g LaCoste"],
	["In Situ/Laboratory Instruments","Photon/Optical Detectors","Optical Particle Counters","1.108","Grimm Technologies Inc."],  # Livre Jean Louis
	["In Situ/Laboratory Instruments","Photon/Optical Detectors","Optical Particle Counters","1.109","Grimm Technologies Inc."],  # Livre Jean Louis
	["In Situ/Laboratory Instruments","Photon/Optical Detectors","Optical Particle Counters","R4903","Met One Instruments"],  # Livre Jean Louis
	["In Situ/Laboratory Instruments","Photon/Optical Detectors","Optical Particle Counters","SID-2","University of Hertfordshire"],  # Livre Jean Louis
	["In Situ/Laboratory Instruments","Photon/Optical Detectors","Tunable Diode Lasers","TDLAS","Imperial College London"],
	["In Situ/Laboratory Instruments","Photon/Optical Detectors","Tunable Diode Lasers","TDLAS","National Physical Laboratory"],
	["In Situ/Laboratory Instruments","Photon/Optical Detectors","Tunable Diode Lasers","WVSS-II","SpectraSensors Inc."],
	["In Situ/Laboratory Instruments","Pressure/Height Meters","Pitot-static Systems","Pitot Probe","Others"],
	["In Situ/Laboratory Instruments","Pressure/Height Meters","Pressure Sensors","1201","Rosemount"],
	["In Situ/Laboratory Instruments","Pressure/Height Meters","Pressure Sensors","1221","Rosemount"],
	["In Situ/Laboratory Instruments","Pressure/Height Meters","Pressure Sensors","Aircraft Systems","Others"],
	["In Situ/Laboratory Instruments","Pressure/Height Meters","Pressure Sensors","Aircraft Systems","Others"],
	["In Situ/Laboratory Instruments","Pressure/Height Meters","Pressure Sensors","B270","Setra Systems"],
	["In Situ/Laboratory Instruments","Pressure/Height Meters","Pressure Sensors","Others","Others"],
	["In Situ/Laboratory Instruments","Pressure/Height Meters","Pressure Sensors","Others","Others"],
	["In Situ/Laboratory Instruments","Pressure/Height Meters","Pressure Sensors","UMP40","Sextant"],
	["In Situ/Laboratory Instruments","Probes","Cloud Droplet Probes","ADA-100-PDPA","TSI Inc."],
	["In Situ/Laboratory Instruments","Probes","Cloud Liquid Water Probes","BCP","Droplet Measurement Technologies"],
	["In Situ/Laboratory Instruments","Probes","Cloud Liquid Water Probes","CDP-2","Droplet Measurement Technologies"],
	["In Situ/Laboratory Instruments","Probes","Cloud Liquid Water Probes","CIP","Droplet Measurement Technologies"],
	["In Situ/Laboratory Instruments","Probes","Cloud Liquid Water Probes","CIP-100","Droplet Measurement Technologies"],
	["In Situ/Laboratory Instruments","Probes","Cloud Liquid Water Probes","CIP-15","Droplet Measurement Technologies"],
	["In Situ/Laboratory Instruments","Probes","Cloud Liquid Water Probes","FSSP-100","Particle Measuring Systems"],
	["In Situ/Laboratory Instruments","Probes","Cloud Liquid Water Probes","FSSP-100ER","Particle Measuring Systems"],
	["In Situ/Laboratory Instruments","Probes","Cloud Liquid Water Probes","FSSP-300","Particle Measuring Systems"],
	["In Situ/Laboratory Instruments","Probes","Cloud Liquid Water Probes","HVPS","Stratton Park Engineering Company"],
	["In Situ/Laboratory Instruments","Probes","Cloud Liquid Water Probes","King Probe","Particle Measuring Systems"],
	["In Situ/Laboratory Instruments","Probes","Cloud Liquid Water Probes","PVM-100","Gerber Scientific Inc."],
	["In Situ/Laboratory Instruments","Probes","Nevzorov Probes","Nevzorov IVO-2a","Sky Tech Research Inc."],
	["In Situ/Laboratory Instruments","Probes","Nevzorov Probes","Nevzorov","Sky Tech Research Inc."],
	["In Situ/Laboratory Instruments","Radiation Sensors","Quantum Sensors","LI-COR Quantum Sensor","LI-COR"],
	["In Situ/Laboratory Instruments","Recorders/Loggers","Automated Weather Systems","Meteorological Sensor Package","DLR"],
	["In Situ/Laboratory Instruments","Recorders/Loggers","Inertial Measurement Units","AIRINS","iXBlue"], #A CORRIGER !!
	["In Situ/Laboratory Instruments","Recorders/Loggers","Inertial Measurement Units","Aircraft Systems","Others"], #A CORRIGER !!
	["In Situ/Laboratory Instruments","Recorders/Loggers","Inertial Measurement Units","CCNS4","IGI mbH"], #A CORRIGER !!
	["In Situ/Laboratory Instruments","Recorders/Loggers","Inertial Measurement Units","High Accuracy INS","SAGEM"], #A CORRIGER !!
	["In Situ/Laboratory Instruments","Recorders/Loggers","Inertial Measurement Units","LTN 90-100","Litton"], #A CORRIGER !!
	["In Situ/Laboratory Instruments","Recorders/Loggers","Inertial Measurement Units","Lasernav YG1761B","Honeywell"], #A CORRIGER !!
	["In Situ/Laboratory Instruments","Recorders/Loggers","Inertial Measurement Units","Others","Others"], #A CORRIGER !!
	["In Situ/Laboratory Instruments","Recorders/Loggers","Inertial Measurement Units","POS AV 510","Applanix"], #A CORRIGER !!
	["In Situ/Laboratory Instruments","Recorders/Loggers","Inertial Measurement Units","POSAV-410","Applanix"], #A CORRIGER !!
	["In Situ/Laboratory Instruments","Recorders/Loggers","Inertial Measurement Units","RT3102","Oxford Technical Solutions"], #A CORRIGER !!
	["In Situ/Laboratory Instruments","Recorders/Loggers","Inertial Measurement Units","ULISS 45i","SAGEM"], #A CORRIGER !!
	["In Situ/Laboratory Instruments","Samplers","Bottles/Flasks/Jars","Flask Array Sampler","Atmospheric Observing Systems Inc."],
	["In Situ/Laboratory Instruments","Samplers","Bottles/Flasks/Jars","Flask Sampling System","MetAir"],
	["In Situ/Laboratory Instruments","Samplers","Grabbers/Traps/Collectors","Filter Sampler","Others"],
	["In Situ/Laboratory Instruments","Samplers","Grabbers/Traps/Collectors","Whole Air Sampling System","University of York"],
	["In Situ/Laboratory Instruments","Spectrometers/Radiometers","Chemiluminescence","MetAir NOxTOy","MetAir AG"],
	["In Situ/Laboratory Instruments","Spectrometers/Radiometers","Chemiluminescence","NO CLD","DLR"],
	["In Situ/Laboratory Instruments","Spectrometers/Radiometers","Chemiluminescence","SIOUX","DLR"],
	["In Situ/Laboratory Instruments","Spectrometers/Radiometers","Chemiluminescence","TECO 42C","ThermoScientific"],
	["In Situ/Laboratory Instruments","Spectrometers/Radiometers","Chemiluminescence","TECO 43C","ThermoScientific"],
	["In Situ/Laboratory Instruments","Spectrometers/Radiometers","Chemiluminescence","TECO 48","ThermoScientific"],
	["In Situ/Laboratory Instruments","Spectrometers/Radiometers","Mass Spectrometers","PTR-MS","University of East Anglia"],
	["In Situ/Laboratory Instruments","Spectrometers/Radiometers","Mass Spectrometers","TOF-AMS","Aerodyne Research Inc."],
	["In Situ/Laboratory Instruments","Spectrometers/Radiometers","Radiometers","Campbell Q7.1","Campbell Scientific"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Hygrometers","1011C","Buck Research Instruments L.L.C."],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Hygrometers","Aircraft systems","Others"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Hygrometers","CR-1","Buck Research Instruments L.L.C."],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Hygrometers","CR-2","Buck Research Instruments L.L.C."],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Hygrometers","Dewtrak-137","EdgeTech Instruments"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Hygrometers","Dewtrak-200","EdgeTech Instruments"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Hygrometers","FS2 Relative Humidity","Aerodata GmbH"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Hygrometers","Flourescence Water Vapour Sensor","Met Office"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Hygrometers","GE-1011B","General Eastern"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Hygrometers","GE-1011C","General Eastern"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Hygrometers","HMP","Vaisala / Rosemount"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Hygrometers","HMP233","Vaisala"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Hygrometers","S3000","Michell Instruments GmbH"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Hygrometers","TP3-S","Meteolabor AG"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Hygrometers","Total Water Content","Met Office"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Lyman-Alpha Hygrometers","Lyman-alpha HMS-2","Buck Research Instruments L.L.C."],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Lyman-Alpha Hygrometers","Lyman-alpha L-5","Buck Research Instruments L.L.C."],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Temperature Sensors","PT","Rosemount"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Temperature Sensors","PT100","Rosemount"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Temperature Sensors","PT102AL","Rosemount"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Temperature Sensors","PT102BL","Rosemount"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Temperature Sensors","PT102BW","Rosemount"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Temperature Sensors","PT102DB1 AG","Rosemount"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Temperature Sensors","PT102E2 AL","Rosemount"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Temperature Sensors","PT102E4 AL","Rosemount"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Temperature Sensors","PT50","Rosemount"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Temperature Sensors","PT500","Rosemount"],
	["Remote Sensing Instruments","Altimeters","Lidar/Laser Altimeters","ALS50","Leica Geosystems"],
	["Remote Sensing Instruments","Altimeters","Lidar/Laser Altimeters","LD90","Riegl Laser Measurement Systems GmbH"],
	["Remote Sensing Instruments","Altimeters","Lidar/Laser Altimeters","LMS-Q280","Riegl Laser Measurement Systems GmbH"],
	["Remote Sensing Instruments","Altimeters","Lidar/Laser Altimeters","LMS-Q560","Riegl Laser Measurement Systems GmbH"],
	["Remote Sensing Instruments","Altimeters","Lidar/Laser Altimeters","LMS-Q680i","Riegl Laser Measurement Systems GmbH"],
	["Remote Sensing Instruments","Altimeters","Lidar/Laser Altimeters","ULS","Laser Technology Inc."],
	["Remote Sensing Instruments","Altimeters","Radar Altimeters","AA-300","Sperry"],
	["Remote Sensing Instruments","Altimeters","Radar Altimeters","AHV16","Thales"],
	["Remote Sensing Instruments","Altimeters","Radar Altimeters","AHV8","TRT"],
	["Remote Sensing Instruments","Altimeters","Radar Altimeters","Aircraft Systems","Others"],
	["Remote Sensing Instruments","Altimeters","Radar Altimeters","KA-131","Bendix King"],
	["Remote Sensing Instruments","Imaging Radars","Imaging Radar Systems","Aircraft Systems","Others"],
	["Remote Sensing Instruments","Imaging Radars","Imaging Radar Systems","RALI","LATMOS"],
	["Remote Sensing Instruments","Imaging Radars","Imaging Radar Systems","RDR-4B","Honeywell"],
	["Remote Sensing Instruments","Imaging Radars","Imaging Radar Systems","Radar Echo Sounding System","AWI"],
	["Remote Sensing Instruments","Imaging Radars","Synthetic Aperture Radars","E-SAR","DLR"],
	["Remote Sensing Instruments","Imaging Radars","Synthetic Aperture Radars","F-SAR","DLR"],
	["Remote Sensing Instruments","Magnetic Field/Electric Field Instruments","Magnetometers","AADC II","Scintrex Ltd"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Cameras","IS-2","Interspect Ltd."],
	["Remote Sensing Instruments","Photon/Optical Detectors","Cameras","RCD105","Leica-Geosystems"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Cameras","RMK A 30/23","Zeiss"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Cameras","RMK A","Zeiss"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Ice Particle Analyzers","CEV","INTA"], # A VERIFIER
	["Remote Sensing Instruments","Photon/Optical Detectors","Ice Particle Analyzers","Ice Nucleus Counter","University of Manchester"], # A VERIFIER
	["Remote Sensing Instruments","Photon/Optical Detectors","Infrared Cameras","FLIR M40","FLIR Systems Inc."], # A VERIFIER
	["Remote Sensing Instruments","Photon/Optical Detectors","Infrared Cameras","FLIR SC3000","FLIR Systems Inc."], # A VERIFIER
	["Remote Sensing Instruments","Photon/Optical Detectors","Infrared Cameras","IRCAM","Jenoptik AG"], # A VERIFIER
	["Remote Sensing Instruments","Photon/Optical Detectors","Multispectral Cameras","IS2+","Interspect Ltd."],
	["Remote Sensing Instruments","Photon/Optical Detectors","Multispectral Cameras","MS4100","Duncantech"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Nephelometers","Airborne Visibility Meter","HSS Inc."],
	["Remote Sensing Instruments","Photon/Optical Detectors","Nephelometers","RR-0150","RadianceResearch"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Nephelometers","TSI-3563","TSI Inc."],
	["Remote Sensing Instruments","Photon/Optical Detectors","Photometers","JO1D / JNO2 Photometer","Unknown"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Video Cameras","GR-DV400","JVC"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Video Cameras","HRSC AX","DLR"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Video Cameras","IS-3","Interspect"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Video Cameras","IS-4","Interspect"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Video Cameras","LTC 0600","Philipps"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Video Cameras","Sony Video Camera","Sony"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Video Cameras","Video Camera","Others"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Video Cameras","dIGIcam K14","IGI mbH"],
	["Remote Sensing Instruments","Positioning/Navigation","Ground Positioning Systems","AT4","Javad GNSS Inc."],
	["Remote Sensing Instruments","Positioning/Navigation","Ground Positioning Systems","Aircraft systems","Others"],
	["Remote Sensing Instruments","Positioning/Navigation","Ground Positioning Systems","Garmin GPS","Garmin"],
	["Remote Sensing Instruments","Positioning/Navigation","Ground Positioning Systems","Gyro-4","Javad GNSS Inc."],
	["Remote Sensing Instruments","Positioning/Navigation","Ground Positioning Systems","OEM4-G2","NovAtel Inc."],
	["Remote Sensing Instruments","Positioning/Navigation","Ground Positioning Systems","Others","Others"],
	["Remote Sensing Instruments","Positioning/Navigation","Ground Positioning Systems","Trimble 2101","Trimble Navigation"],
	["Remote Sensing Instruments","Positioning/Navigation","Ground Positioning Systems","Trimble 4000 SSI","Trimble Navigation"],
	["Remote Sensing Instruments","Positioning/Navigation","Ground Positioning Systems","Trimble TNL 2000","Trimble Navigation"],
	["Remote Sensing Instruments","Positioning/Navigation","Ground Positioning Systems","XR5","Navstar Electronics"],
	["Remote Sensing Instruments","Profilers/Sounders","Dropsondes","AVAPS","Vaisala"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Cloud, Aerosol, Precipitation Spectrometers","CAPS - LWC","Droplet Measurement Technologies"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Cloud, Aerosol, Precipitation Spectrometers","J-W LWC","Johnson-Williams"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Fourier Transform Infrared Spectrometers"," ARIES","Met Office / ABB Bomem"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Fourier Transform Infrared Spectrometers","CRISTA New Frontiers","ForschungsZentrum Juelich"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Fourier Transform Infrared Spectrometers","FTIR","Midac Inc."],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Fourier Transform Infrared Spectrometers","TAFTS","Imperial College London"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Hyperspectral Spectrometers/Radiometers","Airborne Hyperspectral Scanner","Argon ST"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Hyperspectral Spectrometers/Radiometers","AisaDUAL","SPECIM"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Hyperspectral Spectrometers/Radiometers","AisaEAGLE 1K","SPECIM"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Hyperspectral Spectrometers/Radiometers","AisaEAGLE","SPECIM"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Hyperspectral Spectrometers/Radiometers","AisaFENIX 1K","SPECIM"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Hyperspectral Spectrometers/Radiometers","AisaFENIX","SPECIM"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Hyperspectral Spectrometers/Radiometers","AisaOWL","SPECIM"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Hyperspectral Spectrometers/Radiometers","CASI","ITRES Research Ltd"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Hyperspectral Spectrometers/Radiometers","CASI-1500i","ITRES Research Ltd"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Hyperspectral Spectrometers/Radiometers","CASI-550","ITRES Research Ltd"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Hyperspectral Spectrometers/Radiometers","HySpecScan","Analytical Spectral Devices Inc."],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Hyperspectral Spectrometers/Radiometers","IR/UV Line Scanner","OPTIMARE Systems GmbH"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Hyperspectral Spectrometers/Radiometers","PELICAN","IGN"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Imaging Spectrometers/Radiometers","Airborne Prism EXperiment","ESA"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Imaging Spectrometers/Radiometers","Airborne Thematic Mapper","DLR"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Imaging Spectrometers/Radiometers","Polifemo M21","SUPERELECTRIC s.r.l."],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Imaging Spectrometers/Radiometers","TASI-600","ITRES Research Ltd"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Imaging Spectrometers/Radiometers","TS9260","NEC Corporation"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Imaging Spectrometers/Radiometers","VIS Line Scanner","OPTIMARE Systems GmbH"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Infrared Radiometers","Everest 4000.4ZL","Everest Interscience Inc."],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Lidar/Laser Spectrometers","2D-C","Particle Measuring Systems"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Lidar/Laser Spectrometers","2D-P","Particle Measuring Systems"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Lidar/Laser Spectrometers","2D-S","Stratton Park Engineering Company"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Lidar/Laser Spectrometers","2D2C","Particle Measuring Systems"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Lidar/Laser Spectrometers","2DGB2","Particle Measuring Systems"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Lidar/Laser Spectrometers","ALS-450","Leosphere"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Lidar/Laser Spectrometers","ERS microjoule Lidar EMB-ER 1/2","ERS"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Lidar/Laser Spectrometers","OAP-200X","Particle Measuring Systems"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Lidar/Laser Spectrometers","OAP-230X","Particle Measuring Systems"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Lidar/Laser Spectrometers","OAP-230Y","Particle Measuring Systems"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Lidar/Laser Spectrometers","Ozone Lidar EXperiment","DLR"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Lidar/Laser Spectrometers","Portable Lidar System","University of Munich"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Lidar/Laser Spectrometers","RALI","LATMOS"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Lidar/Laser Spectrometers","WIND","DLR / CNRS / INSU"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Microwave Radiometers","DEIMOS","Met Office"], # Livre Jean Louis
	["Remote Sensing Instruments","Spectrometers/Radiometers","Microwave Radiometers","MARSS","Met Office"], # Livre Jean Louis
	["Remote Sensing Instruments","Spectrometers/Radiometers","Spectrometers","FUBISS","Free University of Berlin"], # A AFINER
	["Remote Sensing Instruments","Spectrometers/Radiometers","Spectrometers","FUBISS-ASA2","Free University Berlin"], # A AFINER
	["Remote Sensing Instruments","Spectrometers/Radiometers","Spectrometers","PRT 6","Barnes"], # A AFINER
	["Remote Sensing Instruments","Spectrometers/Radiometers","Spectrometers","SWS","Met Office"], # A AFINER
	["Remote Sensing Instruments","Spectrometers/Radiometers","Spectrometers","TABI320","ITRES Research Ltd"], # A AFINER
	["Remote Sensing Instruments","Spectrometers/Radiometers","Spectrometers","VIS/NIR Spectrometer ","Skye"], # A AFINER
	["Remote Sensing Instruments","Spectrometers/Radiometers","Spectrometers","VIS/NIR Spectrometer","Interspect Ltd."], # A AFINER
	["Remote Sensing Instruments","Spectrometers/Radiometers","Spectrometers","VIS/NIR Spectrometer","OceanOptics"], # A AFINER
	["Remote Sensing Instruments","Spectrometers/Radiometers","Spectroradiometers","4PI-SR","METEO-CONSULT"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Ultraviolet Spectrometers","GASCOD-A","FISBAT-CNR"],
	["Remote Sensing Instruments","Thermal/Radiation Detectors","Pyranometers","CMP-22","Kipp & Zonen"],
	["Remote Sensing Instruments","Thermal/Radiation Detectors","Pyranometers","Eppley PS Pyranometer","The Eppley Laboratory Inc."],
	["Remote Sensing Instruments","Thermal/Radiation Detectors","Pyranometers","LI-COR Pyranometer","LI-COR"],
	["Remote Sensing Instruments","Thermal/Radiation Detectors","Pyranometers","Walz UV Pyranometer","Heinz Walz Company"],
	["Remote Sensing Instruments","Thermal/Radiation Detectors","Pyrgeometers","CGR-4","Kipp & Zonen"],
	["Remote Sensing Instruments","Thermal/Radiation Detectors","Pyrgeometers","Eppley Pyrgeometer","The Eppley Laboratory Inc."],
	["Remote Sensing Instruments","Thermal/Radiation Detectors","Pyrometers","KT-15","Heitronics Infrarot Messtechnik"],
	]'''


intruments_information = [
    ["1.108","Grimm Technologies Inc."],
    ["1.109","Grimm Technologies Inc."],
    ["1011C","Buck Research Instruments L.L.C."],
    ["1201","Rosemount"],
    ["1221","Rosemount"],
    ["2D-C","Particle Measuring Systems"],
    ["2D-P","Particle Measuring Systems"],
    ["2D-S","Stratton Park Engineering Company"],
    ["2D2C","Particle Measuring Systems"],
    ["2DGB2","Particle Measuring Systems"],
    ["3150","ICSensors / Measurement Specialties"],
    ["4PI-SR","METEO-CONSULT"],
    ["5-hole Turbulence Probe","Other"],
    ["858AJ28","Rosemount"],
    ["AA-300","Sperry"],
    ["AADC II","Scintrex Ltd"],
    ["AARP","University of Manchester"],
    ["ADA-100-PDPA","TSI Inc."],
    ["AE-42","Magee Scientific"],
    ["AE-52 Aethelometer","Magee Scientific"],
    ["AHV16","Thales"],
    ["AHV8","TRT"],
    ["AIMMS-20","Aventech Inc."],
    ["AIRINS","iXBlue"],
    ["AL5002","Aero-Laser Gmbh"],
    ["AL5003","Aero-Laser Gmbh"],
    ["ALS-450","Leosphere"],
    ["ALS50","Leica Geosystems"],
    ["ARIES","Met Office / ABB Bomem"],
    ["AT4","Javad GNSS Inc."],
    ["AVAPS","Vaisala"],
    ["Airborne Hyperspectral Scanner","Argon ST"],
    ["Airborne Prism EXperiment","ESA"],
    ["Airborne Thematic Mapper","DLR"],
    ["Airborne Visibility Meter","HSS Inc."],
    ["Aircraft Systems","Other"],
    ["AisaDUAL","SPECIM"],
    ["AisaEAGLE 1K","SPECIM"],
    ["AisaEAGLE","SPECIM"],
    ["AisaFENIX 1K","SPECIM"],
    ["AisaFENIX","SPECIM"],
    ["AisaOWL","SPECIM"],
    ["B270","Setra Systems"],
    ["BAT","NOAA / Airborne Research Australia"],
    ["BCP","Droplet Measurement Technologies"],
    ["CAPS - LWC","Droplet Measurement Technologies"],
    ["CAPS","Droplet Measurement Technologies"],
    ["CAS Spectrometer","Baumgardner et al., 2001"],
    ["CASI","ITRES Research Ltd"],
    ["CASI-1500i","ITRES Research Ltd"],
    ["CASI-550","ITRES Research Ltd"],
    ["CCN Counter","Droplet Measurement Technologies"],
    ["CCNS4","IGI mbH"],
    ["CDP-2","Droplet Measurement Technologies"],
    ["CEV","INTA"],
    ["CGR-4","Kipp & Zonen"],
    ["CIP","Droplet Measurement Technologies"],
    ["CIP-100","Droplet Measurement Technologies"],
    ["CIP-15","Droplet Measurement Technologies"],
    ["CMP-22","Kipp & Zonen"],
    ["COPAS","University of Mainz"],
    ["CPI","Stratton Park Engineering Company"],
    ["CR-1","Buck Research Instruments L.L.C."],
    ["CR-2","Buck Research Instruments L.L.C."],
    ["CRISTA New Frontiers","ForschungsZentrum Juelich"],
    ["CW-QCLAS","Aerodyne Research Inc."],
    ["Campbell Q7.1","Campbell Scientific"],
    ["Cloud Imaging Probe","Other"],
    ["Counterflow Virtual Impactor","Met Office"],
    ["DEIMOS","Met Office"],
    ["Dewtrak-137","EdgeTech Instruments"],
    ["Dewtrak-200","EdgeTech Instruments"],
    ["dIGIcam K14","IGI mbH"],
    ["E-SAR","DLR"],
    ["ERS microjoule Lidar EMB-ER 1/2","ERS"],
    ["Eppley PS Pyranometer","The Eppley Laboratory Inc."],
    ["Eppley Pyrgeometer","The Eppley Laboratory Inc."],
    ["Everest 4000.4ZL","Everest Interscience Inc."],
    ["F-SAR","DLR"],
    ["FAGE","University of Leeds"],
    ["FLIR M40","FLIR Systems Inc."],
    ["FLIR SC3000","FLIR Systems Inc."],
    ["FS2 Relative Humidity","Aerodata GmbH"],
    ["FSSP-100","Particle Measuring Systems"],
    ["FSSP-100ER","Particle Measuring Systems"],
    ["FSSP-300","Particle Measuring Systems"],
    ["FTIR","Midac Inc."],
    ["FUBISS","Free University of Berlin"],
    ["FUBISS-ASA2","Free University Berlin"],
    ["Filter Sampler","Other"],
    ["Flask Array Sampler","Atmospheric Observing Systems Inc."],
    ["Flask Sampling System","MetAir"],
    ["Flourescence Water Vapour Sensor","Met Office"],
    ["Formaldehyde Detectors","Other"],
    ["GASCOD-A","FISBAT-CNR"],
    ["GE-1011B","General Eastern"],
    ["GE-1011C","General Eastern"],
    ["GR-DV400","JVC"],
    ["Garmin GPS","Garmin"],
    ["Gyro-4","Javad GNSS Inc."],
    ["HAGAR","University of Frankfurt"],
    ["HALOX","Forschungszentrum Julich GmbH"],
    ["HMP","Vaisala / Rosemount"],
    ["HMP233","Vaisala"],
    ["HRSC AX","DLR"],
    ["HVPS","Stratton Park Engineering Company"],
    ["High Accuracy INS","SAGEM"],
    ["Hyperspectral Imagery Sensor","DLR"],
    ["HySpecScan","Analytical Spectral Devices Inc."],
    ["IR Gas analyzer","Edinburgh Sensors"],
    ["IR/UV Line Scanner","OPTIMARE Systems GmbH"],
    ["IRCAM","Jenoptik AG"],
    ["IS-2","Interspect Ltd."],
    ["IS-3","Interspect Ltd."],
    ["IS-4","Interspect Ltd."],
    ["IS2+","Interspect Ltd."],
    ["Ice Nucleus Counter","University of Manchester"],
    ["J-W LWC","Johnson-Williams"],
    ["JO1D / JNO2 Photometer","Unknown"],
    ["KA-131","Bendix King"],
    ["KT-15","Heitronics Infrarot Messtechnik"],
    ["King Probe","Particle Measuring Systems"],
    ["Kistler 3 axes accelerometers","Kistler Instrumente AG"],
    ["LASAIR-5295","Particle Measurement Systems"],
    ["LD90","Riegl Laser Measurement Systems GmbH"],
    ["LGR 907","Los Gatos Research Inc."],
    ["LGR DLT100","Los Gatos Research Inc."],
    ["LI-COR 6262","LI-COR"],
    ["LI-COR 7500","LI-COR"],
    ["LI-COR Pyranometer","LI-COR"],
    ["LI-COR Quantum Sensor","LI-COR"],
    ["LMS-Q280","Riegl Laser Measurement Systems GmbH"],
    ["LMS-Q560","Riegl Laser Measurement Systems GmbH"],
    ["LMS-Q680i","Riegl Laser Measurement Systems GmbH"],
    ["LTC 0600","Philipps"],
    ["LTN 90-100","Litton"],
    ["Lasernav YG1761B","Honeywell"],
    ["Lyman-alpha HMS-2","Buck Research Instruments L.L.C."],
    ["Lyman-alpha L-5","Buck Research Instruments L.L.C."],
    ["MARSS","Met Office"],
    ["MS4100","Duncantech"],
    ["MetAir NOxTOy","MetAir AG"],
    ["Meteorological Sensor Package","DLR"],
    ["Mobile Flux Platform","IBIMET CNR"],
    ["NO CLD","DLR"],
    ["Nevzorov IVO-2a","Sky Tech Research Inc."],
    ["Nevzorov","Sky Tech Research Inc."],
    ["OAP-200X","Particle Measuring Systems"],
    ["OAP-230X","Particle Measuring Systems"],
    ["OAP-230Y","Particle Measuring Systems"],
    ["OEM4-G2","NovAtel Inc."],
    ["ORAC","University of Leeds"],
    ["Others","Other"],
    ["Ozone Lidar EXperiment","DLR"],
    ["Ozone Monitor 202","2B Technologies"],
    ["Ozone Monitor","2B Technologies"],
    ["PAN GC","Ai Qualitek Ltd"],
    ["PCASP-100X","Droplet Measurement Technologies"],
    ["PCASP-SPP200","Droplet Measurement Technologies"],
    ["PELICAN","ONERA"],
    ["PERCA","University of Leceister"],
    ["POS AV 510","Applanix"],
    ["POSAV-410","Applanix"],
    ["PRT 6","Barnes"],
    ["PSAP","Radiance Research Inc."],
    ["PSI-O3","Paul Scherrer Institut"],
    ["PT","Rosemount"],
    ["PT100","Rosemount"],
    ["PT102AL","Rosemount"],
    ["PT102BL","Rosemount"],
    ["PT102BW","Rosemount"],
    ["PT102DB1 AG","Rosemount"],
    ["PT102E2 AL","Rosemount"],
    ["PT102E4 AL","Rosemount"],
    ["PT50","Rosemount"],
    ["PT500","Rosemount"],
    ["PTR-MS","University of East Anglia"],
    ["PVM-100","Gerber Scientific Inc."],
    ["Peroxide Detectors","Other"],
    ["Pitot Probe","Other"],
    ["Polifemo M21","SUPERELECTRIC s.r.l."],
    ["Portable Lidar System","University of Munich"],
    ["R4903","Met One Instruments"],
    ["RALI","LATMOS"],
    ["RALI","LATMOS"],
    ["RCD105","Leica-Geosystems"],
    ["RDR-4B","Honeywell"],
    ["RMK A 30/23","Zeiss"],
    ["RMK A","Zeiss"],
    ["RR-0150","RadianceResearch"],
    ["RT3102","Oxford Technical Solutions"],
    ["Radar Echo Sounding System","AWI"],
    ["S-5002","Sistemas Instalaciones Redes S.A."],
    ["S-5006","Sistemas Instalaciones Redes S.A."],
    ["S-5012","Sistemas Instalaciones Redes S.A."],
    ["S3000","Michell Instruments GmbH"],
    ["S56","Micro-g LaCoste"],
    ["SA 41M","Environment S.A."],
    ["SETHI","ONERA"],
    ["SFIM 3 axes accelerometers","SFIM"],
    ["SID-2","University of Hertfordshire"],
    ["SIELETERS","ONERA"],
    ["SIOUX","DLR"],
    ["SMPS","Grimm Technologies Inc."],
    ["SP-2","Droplet Measurement Technologies"],
    ["SPEC Hawkeye","Stratton Park Engineering Company"],
    ["SWS","Met Office"],
    ["Solent HS","Gill Instruments Ltd"],
    ["Solent HS-100","Gill Instruments Ltd"],
    ["Solent HS-50","Gill Instruments Ltd"],
    ["Sony Video Camera","Sony"],
    ["Sundstrand 3 axes accelerometers","Sundstrand"],
    ["TABI320","ITRES Research Ltd"],
    ["TAFTS","Imperial College London"],
    ["TASI-600","ITRES Research Ltd"],
    ["TDLAS","Imperial College London"],
    ["TDLAS","National Physical Laboratory"],
    ["TECO 42C","ThermoScientific"],
    ["TECO 42C","ThermoScientific"],
    ["TECO 42S","ThermoScientific"],
    ["TECO 43C","ThermoScientific"],
    ["TECO 48","ThermoScientific"],
    ["TECO 48CS","ThermoScientific"],
    ["TECO 49PS","ThermoScientific"],
    ["TECO 49S","ThermoScientific"],
    ["TOF-AMS","Aerodyne Research Inc."],
    ["TP3-S","Meteolabor AG"],
    ["TS9260","NEC Corporation"],
    ["TSI-3007","TSI Inc."],
    ["TSI-3010","TSI Inc."],
    ["TSI-3022","TSI Inc."],
    ["TSI-3025","TSI Inc."],
    ["TSI-3563","TSI Inc."],
    ["TSI-3776","TSI Inc."],
    ["TSI-3786","TSI Inc."],
    ["Total Water Content","Met Office"],
    ["Trimble 2101","Trimble Navigation"],
    ["Trimble 4000 SSI","Trimble Navigation"],
    ["Trimble TNL 2000","Trimble Navigation"],
    ["UHSAS-A","Droplet Measurement Technologies"],
    ["ULISS 45i","SAGEM"],
    ["ULS","Laser Technology Inc."],
    ["UMP40","Sextant"],
    ["VACC","University of Leeds"],
    ["VIS Line Scanner","OPTIMARE Systems GmbH"],
    ["VIS/NIR Spectrometer ","Other"],
    ["VOC GC","Airmotec AG"],
    ["Video Camera","Other"],
    ["WIND","DLR / CNRS / INSU"],
    ["WVSS-II","SpectraSensors Inc."],
    ["Walz UV Pyranometer","Heinz Walz Company"],
    ["Whole Air Sampling System","University of York"],
    ["XR5","Navstar Electronics"],
    ]


instruments_classification = [
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Aerosol Monitors"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Aethalometers"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Air Permeameters"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","CHN Analyzers"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","CO2 Analyzers"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Carbon Analyzers"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Carbon, Hydrogen, Nitrogen Analyzers"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Condensation Nuclei Counter"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Fluorometers"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Gas Sensors"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Gaz Chromatographs"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Gaz Correlation Filters"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Infrared Gas Analyzer"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Ion Chromatographs"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Liquid Chromatographs"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Neutron Monitors"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Nondispersive Infrared Gas Analyzers"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Oxygen Analyzers"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Ozone Monitors"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Porometers"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","pH Meters"],
	["In Situ/Laboratory Instruments","Conductivity Sensors","Conductivity Meters"],
	["In Situ/Laboratory Instruments","Current/Wind Meters","Counterflow Virtual Impactors"],
	["In Situ/Laboratory Instruments","Current/Wind Meters","Wind Monitors"],
	["In Situ/Laboratory Instruments","Magnetic/Motion Sensors","Accelerographs"],
	["In Situ/Laboratory Instruments","Magnetic/Motion Sensors","Accelerometers"],
	["In Situ/Laboratory Instruments","Magnetic/Motion Sensors","Gravimeters"],
	["In Situ/Laboratory Instruments","Magnetic/Motion Sensors","Inclinometers"],
	["In Situ/Laboratory Instruments","Photon/Optical Detectors ","Tunable Diode Lasers"],
	["In Situ/Laboratory Instruments","Photon/Optical Detectors","Binoculars"],
	["In Situ/Laboratory Instruments","Photon/Optical Detectors","Cameras"],
	["In Situ/Laboratory Instruments","Photon/Optical Detectors","Optical Particle Counters"],  # Livre Jean Louis
	["In Situ/Laboratory Instruments","Photon/Optical Detectors","Turbidity Meters"],
	["In Situ/Laboratory Instruments","Photon/Optical Detectors","Visual Observations"],
	["In Situ/Laboratory Instruments","Pressure/Height Meters","Barometers"],
	["In Situ/Laboratory Instruments","Pressure/Height Meters","Microbarographs"],
	["In Situ/Laboratory Instruments","Pressure/Height Meters","Pitot-static System"],
	["In Situ/Laboratory Instruments","Pressure/Height Meters","Pressure Sensors"],
	["In Situ/Laboratory Instruments","Probes","Cloud Droplet Probes"],
	["In Situ/Laboratory Instruments","Probes","Cloud Liquid Water Probes"],
	["In Situ/Laboratory Instruments","Probes","Dielectric Probes"],
	["In Situ/Laboratory Instruments","Probes","Neutron Probes"],
	["In Situ/Laboratory Instruments","Probes","Nevzorov Probes"],
	["In Situ/Laboratory Instruments","Probes","Probes"],
	["In Situ/Laboratory Instruments","Probes","Temperature Probes"],
	["In Situ/Laboratory Instruments","Radiation Sensors","Quantum Sensors"],
	["In Situ/Laboratory Instruments","Samplers","Bottles / Flasks / Jars"],
	["In Situ/Laboratory Instruments","Samplers","Grabbers /Traps / Collectors"],
	["In Situ/Laboratory Instruments","Spectrometers/Radiometers","Chemiluminescence"],
	["In Situ/Laboratory Instruments","Spectrometers/Radiometers","Colorimeters"],
	["In Situ/Laboratory Instruments","Spectrometers/Radiometers","Mass Spectrometers"],
	["In Situ/Laboratory Instruments","Spectrometers/Radiometers","Net Radiometers"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Humidity Sensors"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Humidity Transducers"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Hydrometers"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Hygrometers"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Hypsometers"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Psychrometers"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Soil Heat Flux Transducers"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Temperature Sensors"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Thermistors"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Thermometers"],
	["Remote Sensing Instruments","Altimeters","Lidar/Laser Altimeters"],
	["Remote Sensing Instruments","Altimeters","Radar Altimeters"],
	["Remote Sensing Instruments","Imaging Radars","Active Microwave Instruments"],
	["Remote Sensing Instruments","Imaging Radars","Advanced SAR"],
	["Remote Sensing Instruments","Imaging Radars","Airborn SAR"],
	["Remote Sensing Instruments","Imaging Radars","C-Band SAR"],
	["Remote Sensing Instruments","Imaging Radars","Phased Array type L-band SAR"],
	["Remote Sensing Instruments","Imaging Radars","SAR"],
	["Remote Sensing Instruments","Imaging Radars","Side-Looking Airborne Radars"],
	["Remote Sensing Instruments","Imaging Radars","Water Content Reflectometers"],
	["Remote Sensing Instruments","Imaging Radars","X-Band SAR"],
	["Remote Sensing Instruments","Magnetic/Electric Field Instruments","Magnetic Variometers"],
	["Remote Sensing Instruments","Magnetic/Electric Field Instruments","Magnetometers"],
	["Remote Sensing Instruments","Magnetic/Electric Field Instruments","Nuclear Precession Magnetometers"],
	["Remote Sensing Instruments","Magnetic/Electric Field Instruments","Overhauser Scalar Magnetometers"],
	["Remote Sensing Instruments","Magnetic/Electric Field Instruments","Proton Magnetometers"],
	["Remote Sensing Instruments","Magnetic/Motion Sensors","Accelerometers"],
	["Remote Sensing Instruments","Magnetic/Motion Sensors","Gravimeters"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Cameras"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Ceilometers"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Gas Filter Correlated Radiometer"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Monochromators"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Nephelometers"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Particle Detectors"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Photoelectric Aerosol Sensor"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Photometers"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Polarimeters"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Scintillation Counters"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Sunshine Recorders"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Video Cameras"],
	["Remote Sensing Instruments","Positioning/Navigation","Compasses"],
	["Remote Sensing Instruments","Positioning/Navigation","Ground Positioning Systems"],
	["Remote Sensing Instruments","Positioning/Navigation","Gyros"],
	["Remote Sensing Instruments","Positioning/Navigation","RF Antennas"],
	["Remote Sensing Instruments","Positioning/Navigation","Radars"],
	["Remote Sensing Instruments","Positioning/Navigation","Transponders"],
	["Remote Sensing Instruments","Positioning/Navigation","VLF Receivers"],
	["Remote Sensing Instruments","Scatterometers","Advance Scatterometers"],
	["Remote Sensing Instruments","Scatterometers","Aquarius Scatterometers"],
	["Remote Sensing Instruments","Scatterometers","SEASAT-A Scatterometer"],
	["Remote Sensing Instruments","Scatterometers","Scatterometers"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Cloud, Aerosol, Precipitation Spectrometers"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Fourier Transform Infrared Spectrometers"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Hyperspectral Spectrometers / Radiometer"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Imaging Spectrometers/Radiometers"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Infrared Radiometers"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Interferometers"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Lidar/Laser Spectrometers"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Microwave Radiometers"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Radiometers"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Spectrometers"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Spectroradiometers"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Ultraviolet Spectrometers"],
	["Remote Sensing Instruments","Thermal/Radiation Detectors","Actinometers"],
	["Remote Sensing Instruments","Thermal/Radiation Detectors","Bolometers"],
	["Remote Sensing Instruments","Thermal/Radiation Detectors","Pygeometers"],
	["Remote Sensing Instruments","Thermal/Radiation Detectors","Pyranometers"],
	["Remote Sensing Instruments","Thermal/Radiation Detectors","Pyrheliometers"],
	["Remote Sensing Instruments","Thermal/Radiation Detectors","Pyrometers"],
	["Remote Sensing Instruments","Thermal/Radiation Detectors","Pyrradiometers"],
	["Remote Sensing Instruments","Thermal/Radiation Detectors","Solarimeters"],
	]


elements_informations = [
	["5","cl_label_1","Topic Category","Classification",""],
	["6","kw_category_lb1","Keywords","Keywords",""],
	["1","id_resourceTitle_ln","Resource title","Identification","text"],
	["2","id_resourceAbstract_ta","Resource abstract","Identification","text"],
	["3","id_resourceLocator_ln","Resource locator","Identification","text"],
	["4","id_resourceIdent_ln","Unique resource identifier","Identification","text"],
	["8","ai_label_1","Aircraft","Aircraft and Instruments",""],
    
    ["8.1","ai_manufacturer_ln","Aircraft - Manufacturer","Aircraft and Instruments","text"],
    ["8.2","ai_type_ln","Aircraft - Type","Aircraft and Instruments","text"],
    ["8.3","ai_operator_ln","Aircraft - Operator","Aircraft and Instruments","text"],
    ["8.4","ai_country_lb","Aircraft - Country","Aircraft and Instruments",""],
    ["8.5","ai_number_ln","Aircraft - Registration number","Aircraft and Instruments","text"],
    
	["9","ai_label_13","Instrument","Aircraft and Instruments",""],
    ["9.1","ai_newname_ln","Instrument - Name","Aircraft and Instruments","text"],
    ["9.2","ai_newmanufacturer_ln","Instrument - Manufacturer","Aircraft and Instruments","text"],
    
	["10","gl_location_lb","Location","Geographic Information",""],
	["11","gl_northBound_ln","Geographic bounding box - North","Geographic Information","float"],
	["12","gl_southBound_ln","Geographic bounding box - South","Geographic Information","float"],
	["13","gl_eastBound_ln","Geographic bounding box - East","Geographic Information","float"],
	["14","gl_westBound_ln","Geographic bounding box - West","Geographic Information","float"],
	["15","gl_resolution_ln","Spatial Resolution","Geographic Information","float"],
	["16","gl_unit_ln","Spatial Resolution - Unit","Geographic Information","text"],
	["17","tr_datePublication_do","Date of publication","Temporal Reference","date"],
	["18","tr_dateRevision_do","Date of last revision","Temporal Reference","date"],
	["19","tr_dateCreation_do","Date of creation","Temporal Reference","date"],
	["20","tr_temporal_extent","Temporal extent - Phase 1","Temporal Reference","date"],
    
    ["21","qv_insituLab","Selection of the domain","Quality and Validity",""],
    ["22","qv_insituCalDesc_ln","Link to the procedure's description","Quality and Validity","text"],
    ["23","qv_insituCalCons_ln","Source of constants","Quality and Validity","text"],
    ["24","qv_insituCalMat_ln","Source of materials","Quality and Validity","text"],
    ["25","qv_insituGeoUni","Conversion to geophysical units","Quality and Validity",""],
    ["26","qv_insituOutFormat","Output in standardized format","Quality and Validity",""],
    ["27","qv_insituOutFormat_ln","Output in standardized format - Other","Quality and Validity","text"],
    ["28","qv_insituQuaFlag_ln","Quality-control flagging","Quality and Validity","text"],
    ["29","qv_insituAssumption_ln","Assumption","Quality and Validity","text"],
    
    ["21","qv_obsCalLabo_ln","Name of calibration laboratory","Quality and Validity","text"],
    ["22","qv_obsRadCal_do1","Date of radiometric calibration","Quality and Validity","date"],
    ["23","qv_obsSpeCal_do2","Date of spectral calibration","Quality and Validity","date"],
    ["24","qv_obsSpeBand_ln","Number of spectral bands","Quality and Validity","float"],
    ["25","qv_obsFltHdg_ln","Overall fligh direction","Quality and Validity","float"],
    ["26","qv_obsFltAlt_ln","Overall altitude ASL","Quality and Validity","float"],
    ["27","qv_obsSolZen_ln","Solar zenith","Quality and Validity","float"],
    ["28","qv_obsSolAzi_ln","Solar azimuth","Quality and Validity","float"],
    ["29","qv_obsAnoAcq_ln","Report anomalies in data acquisition","Quality and Validity","text"],
    ["30","qv_obsProLvl","Processing level","Quality and Validity",""],
    ["31","qv_obsDrkCur","Dark current correction","Quality and Validity",""],
    ["32","qv_obsIntMask","Aggregated interpolated pixel mask","Quality and Validity",""],
    ["33","qv_obsBadMask","Aggregated bad pixel mask","Quality and Validity",""],
    ["34","qv_obsSatPix","Saturated pixels / overflow","Quality and Validity",""],
    ["35","qv_obsSpeNeigh","Pixels affected by saturation","Quality and Validity",""],
    ["36","qv_obsPosInfo","Problems with position information","Quality and Validity",""],
    ["37","qv_obsAttInfo","Problems with attitude information","Quality and Validity",""],
    ["38","qv_obsSynProb","Synchronization problems","Quality and Validity",""],
    ["39","qv_obsIntGeo","Interpolated pixels during geocoding","Quality and Validity",""],
    ["40","qv_obsAtmCorr","Failure of atmospheric correction","Quality and Validity",""],
    ["41","qv_obsCldMask","Cloud mask","Quality and Validity",""],
    ["42","qv_obsShdMask","Cloud shadow mask","Quality and Validity",""],
    ["43","qv_obsHazMask","Haze mask","Quality and Validity",""],
    ["44","qv_obsDEMMea","Terrain correction based on DEM roughness measure","Quality and Validity",""],
    ["45","qv_obsIllAng","Terrain correction based on illumination angle","Quality and Validity",""],
    ["46","qv_obsBRDFGeo","BRDF geometry based on sun-sensor-terrain geometry","Quality and Validity",""],
    
	["47","au_conditions_ta","Conditions applying to access and use","Access and Use Constraints","text"],
	["48","au_limitations_ta","Limitations on public access","Access and Use Constraints","text"],
	["49","au_wn_con_ta","Conditions applying to access and use","Access and Use Constraints","text"],
	["50","au_wn_lim_ta","Limitations on public access","Access and Use Constraints","text"],
	["51","ro_responsibleParty_ln","Responsible party","Responsible Organisations","text"],
	["52","ro_responsibleEmail_ln","Responsible party e-mail","Responsible Organisations","text"],
	["53","ro_rlPy_ln","Responsible party","Responsible Organisations","text"],
	["54","ro_rlEm_ln","Responsible party e-mail","Responsible Organisations","text"],
	["55","mm_date_do","Metadata date","Metadata on Metadata","date"],
	["56","mm_contactName_ln","Name","Metadata on Metadata","text"],
	["57","mm_contactEmail_ln","E-mail","Metadata on Metadata","text"],
	["58","mm_conName_ln","Name","Metadata on Metadata","text"],
	["59","mm_conEmail_ln","E-mail","Metadata on Metadata","text"],
	]

path = os.getcwd()

if path == "/home/henryo/Travail/python/EUFAR_metadata_creator":
    path += "/sqlite"

con = lite.connect(path + "/emc_database.db")  # @UndefinedVariable
con.text_factory = str


with con:
    
    cur = con.cursor()    
    cur.execute("DROP TABLE IF EXISTS aircraftInformations")
    cur.execute("CREATE TABLE aircraftInformations(Id TEXT, Manufacturer TEXT, Type TEXT, Operator TEXT, Country TEXT, Code TEXT, Image TEXT, Copyright TEXT)")
    cur.executemany("INSERT INTO aircraftInformations VALUES(?, ?, ?, ?, ?, ?, ?, ?)", aircraft_informations)
    
    cur = con.cursor()    
    cur.execute("DROP TABLE IF EXISTS languageRole")
    cur.execute("CREATE TABLE languageRole(Id TEXT, Short TEXT)")
    cur.executemany("INSERT INTO languageRole VALUES(?, ?)", language_role_dict)
    
    cur = con.cursor()    
    cur.execute("DROP TABLE IF EXISTS unit")
    cur.execute("CREATE TABLE unit(Main TEXT, Short TEXT)")
    cur.executemany("INSERT INTO unit VALUES(?, ?)", unit_dict)
    
    cur = con.cursor()    
    cur.execute("DROP TABLE IF EXISTS windowsMessage")
    cur.execute("CREATE TABLE windowsMessage(Button TEXT, Message TEXT)")
    cur.executemany("INSERT INTO windowsMessage VALUES(?, ?)", window_messages)
    
    cur = con.cursor()    
    cur.execute("DROP TABLE IF EXISTS instrumentsInformations")
    cur.execute("CREATE TABLE instrumentsInformations(Model TEXT, Manufacturer TEXT)")
    cur.executemany("INSERT INTO instrumentsInformations VALUES(?, ?)", intruments_information)
    
    cur = con.cursor()    
    cur.execute("DROP TABLE IF EXISTS topics")
    cur.execute("CREATE TABLE topics(Text TEXT, Value TEXT)")
    cur.executemany("INSERT INTO topics VALUES(?, ?)", topic_dict)
    
    cur = con.cursor()    
    cur.execute("DROP TABLE IF EXISTS instrumentsClassification")
    cur.execute("CREATE TABLE instrumentsClassification(Domain TEXT, Category TEXT, Type TEXT)")
    cur.executemany("INSERT INTO instrumentsClassification VALUES(?, ?, ?)", instruments_classification)
    
    cur = con.cursor()    
    cur.execute("DROP TABLE IF EXISTS elementsInformation")
    cur.execute("CREATE TABLE elementsInformation(Place INT, Object TEXT, Name TEXT, Page TEXT, Type TEXT)")
    cur.executemany("INSERT INTO elementsInformation VALUES(?, ?, ?, ?, ?)", elements_informations)
    
    cur = con.cursor()    
    cur.execute("DROP TABLE IF EXISTS emcLocations")
    cur.execute("CREATE TABLE emcLocations(Category TEXT, Detail TEXT)")
    cur.executemany("INSERT INTO emcLocations VALUES(?, ?)", emc_locations)
    
    cur = con.cursor()    
    cur.execute("DROP TABLE IF EXISTS scienceKeywords")
    cur.execute("CREATE TABLE scienceKeywords(Category TEXT, Keywords TEXT, Labels TEXT)")
    cur.executemany("INSERT INTO scienceKeywords VALUES(?, ?, ?)", ceos_science_keywords)
 
    
con.close()