# -*- coding: utf-8 -*-

# EMC is using a database to store all needed information about aircraft, operators, keywords, instruments and so on. Use this program to generate the database


import sqlite3 as lite
import sys, os


aircraft_informations = (
	("AWI - POLAR 5", "Basler Turbo Conversions", "BT-67", "Alfred Wegener Institute (AWI)", "Germany", "C-GAWI", "POLAR5-AWI.png", "Alfred Wegener Institute"),
	("CNR - ERA Skyarrow", "3I / Magnaghi Aeronautica", "Sky Arrow 650", "Consiglio Nazionale delle Ricerche (CNR) - ISAFoM", "Italy", "I-AMMO", "ERA-ISAFM.png", "CNR, Istituto per i Sistemi Agricoli e Forestali del Mediterraneo"),
	("CNR - Partenavia", "Partenavia / Vulcanair", "P-68", "Consiglio Nazionale delle Ricerche (CNR) - IMAA", "Italy", "I-ALTM", "PARTENAVIA-CNR.png", "CNR, Istituto di Metodologie per l'Analisi Ambientale"),
	("DLR - C 208", "Cessna Aircraft Company", "Cessna 208", "Deutsches Zentrum fur Luft- und Raumfahrt (DLR)", "Germany", "D-FDLR", "C208-DLR.png", "DLR, CC-BY 3.0"),
	("DLR - DO 228 D-CFFU", "Dornier Flugzeugwerke", "DO-228", "Deutsches Zentrum fur Luft- und Raumfahrt (DLR)", "Germany", "D-CFFU", "DO228-DLR-1.png", "DLR, CC-BY 3.0"),
	("DLR - DO 228 D-CODE", "Dornier Flugzeugwer	ke", "DO-228", "Deutsches Zentrum fur Luft- und Raumfahrt (DLR)", "Germany", "D-CODE", "DLR - DO228-2.png", "DLR, CC-BY 3.0"),
	("DLR - Falcon 20", "Dassault Aviation", "Mystere/Falcon 20", "Deutsches Zentrum fur Luft- und Raumfahrt (DLR)", "Germany", "D-CMET", "FALCON20-DLR.png", "DLR, CC-BY 3.0"),
	("Do your choice ...", " ", " ", " ", " ", " ", "logo_eufar_emc.png", " "),
	("ENVISCOPE - Learjet 35", "Learjet Aircraft Company", "Learjet 35", "ENVISCOPE", "Germany", "D-CGFD", "LEARJET25-ENVISCOPE-3.png", "ENVISCOPE GmbH"),
	("ENVISCOPE - Partenavia", "Partenavia / Vulcanair", "P-68", "ENVISCOPE", "Germany", "D-GERY", "PARTENAVIA68-ENVISCOPE-2.png", "ENVISCOPE GmbH"),
	("FAAM - BAe 146", "BAE Systems", "BAe-146", "Facility for Airborne Atmospheric Measurements (FAAM)", "United Kingdom", "G-LUXE", "BAE146-FAAM.png", "NERC, Facility for Airborne Atmospheric Measurements"),
	("FUB - C 207", "Cessna Aircraft Company", "Cessna 207", "Freie Universitat Berlin (FUB) - ISS", "Germany", "D-EAFU", "C207-FUB.png", "Institut fur Weltraumwissenschaften"),
	("INTA - CASA 212 AR", "Construcciones Aeronauticas S.A.", "CASA-212", "Instituto Nacional de Tecnica Aeroespacial (INTA)", "Spain", "EC-DTV", "CASA212-INTA.png", "Instituto Nacional de Tecnica Aeroespacial"),
	("INTA - CASA 212 RS", "Construcciones Aeronauticas S.A.", "CASA-212", "Instituto Nacional de Tecnica Aeroespacial (INTA)", "Spain", "EC-DUQ", "CASA212-INTA.png", "Instituto Nacional de Tecnica Aeroespacial"),
	("KIT - Enduro", "Ultraleichtflug Schmidtler", "Enduro", "Karlsruhe Institute of Technology (KIT) - IMK-IFU", "Germany", "D-MIFU", "ENDURO-KIT.png","KIT, Institute of Meteorology and Climate Research"),
	("NERC - DO 228", "Dornier Flugzeugwerke", "DO-228", "Natural Environment Research Council (NERC) - ARSF", "United Kingdom", "EC-DUQ", "DO228-NERC.png", "NERC, Airborne Research and Survey Facility"),
	("NERC - Twin Otter", "De Havilland Canada", "DHC-6", "Natural Environment Research Council (NERC) - BAS", "United Kingdom", "VP-FAZ", "TWINOTTER-NERC.png", "NERC, British Antarctic Survey"),
	("SAFIRE - ATR 42", "ATR", "ATR-42", "SAFIRE", "France", "F-HMTO", "ATR42-SAFIRE.png", "SAFIRE"),
	("SAFIRE - Falcon 20", "Dassault Aviation", "Mystere/Falcon 20", "SAFIRE", "France", "F-GBTM", "FALCON20-SAFIRE-3.png", "Collection Saspozatlse"),
	("SAFIRE - PIPER Aztec", "Piper Aircraft", "PA23", "SAFIRE", "France", "F-BLEB", "PIPERAZTEC-SAFIRE.png", "SAFIRE"),
	("UEDIN - ECO Dimona", "Diamond Aircraft Industries", "HK36TTC ECO Dimona", "The University of Edinburgh (UEDIN) - IAES", "United Kingdom", "G-GEOS", "DIAMOND-UEDIN-1.png", "UEDIN, Airborne GeoSciences"),
	)


topic_dict = (
	("Biota","biota"),
	("Boundaries","boundaries"),
	("Climatology / Meteorology / Atmosphere","climatologyMeteorologyAtmosphere"),
	("Economy","economy"),
	("Elevation","elevation"),
	("Environment","environment"),
	("Farming","farming"),
	("Geoscientific Information","geoscientificInformation"),
	("Health","health"),
	("Imagery / Base Maps / Earth Cover","imageryBaseMapsEarthCover"),
	("Intelligence / Military","intelligenceMilitary"),
	("Inland Waters","inlandWaters"),
	("Location","location"),
	("Oceans","oceans"),
	("Planning / Cadastre","planningCadastre"),
	("Society","society"),
	("Structure","structure"),
	("Transportation","transportation"),
	("Utilities / Communication","utilitiesCommunication")
	)


language_role_dict = (
	('Bulgarian','bul'),
	('Czech','ces'),
	('Danish','dan'),
	('Dutch','dut'),
	('English','eng'),
	('Estonian','est'),
	('Finnish','fin'),
	('French','fra'),
	('German','ger'),
	('Greek','gre'),
	('Hungarian','hun'),
	('Irish','gle'),
	('Italian','ita'),
	('Latvian','lav'),
	('Lithuanian','lit'),
	('Maltese','mlt'),
	('Polish','pol'),
	('Portuguese','por'),
	('Romanian','rum'),
	('Slovak','slo'),
	('Slovenian', 'slv'),
	('Spanish','spa'),
	('Swedish','swe'),
	('Author','author'),
	('Custodian','custodian'),
	('Distributor','distributor'),
	('Originator','originator'),
	('Owner','owner'),
	('Point of Contact','pointOfContact'),
	('Principal Investigator','principalInvestigator'),
	('Processor','processor'),
	('Publisher','publisher'),
	('Resource Provider','resourceProvider'),
	('User','user'),
	('Alfred Wegener Institute (AWI)','AWI'),
	('Consiglio Nazionale delle Ricerche (CNR) - ISAFoM','CNR-ISAFoM'),
	('Consiglio Nazionale delle Ricerche (CNR) - IMAA','CNR-IMAA'),
	('Deutsches Zentrum fur Luft- und Raumfahrt (DLR)','DLR'),
	('ENVISCOPE','Enviscope'),
	('Facility for Airborne Atmospheric Measurements (FAAM)','FAAM'),
	('Freie Universitat Berlin (FUB) - ISS','FUB-ISS'),
	('Instituto Nacional de Tecnica Aeroespacial (INTA)','INTA'),
	('Karlsruhe Institute of Technology (KIT) - IMK-IFU','KIT-IMK-IFU'),
	('Natural Environment Research Council (NERC) - ARSF','NERC-ARSF'),
	('Natural Environment Research Council (NERC) - BAS','NERC-BAS'),
	('SAFIRE','SAFIRE'),
	('The University of Edinburgh (UEDIN) - IAES','UEDIN-IAES')
	)


ceos_science_keywords = [
	["Agriculture","Agricultural aquatic sciences",""],
	["Agriculture","Agricultural chemicals",""],
	["Agriculture","Agricultural engineering","kw_agriEngineering_ck"],
	["Agriculture","Agricultural plant science","kw_agriPlant_ck"],
	["Agriculture","Animal commodities",""],
	["Agriculture","Animal science",""],
	["Agriculture","Feed products",""],
	["Agriculture","Food science","kw_foodScience_ck"],
	["Agriculture","Forest science","kw_forestScience_ck"],
	["Agriculture","Plant commodities",""],
	["Agriculture","Soils","kw_soils_ck"],
	["Atmosphere","Aerosols","kw_aerosols_ck"],
	["Atmosphere","Air quality","kw_airQuality_ck"],
	["Atmosphere","Altitude","kw_altitude_ck"],
	["Atmosphere","Atmospheric chemistry","kw_atmChemistry_ck"],
	["Atmosphere","Atmospheric electricity","kw_atmElectricity_ck"],
	["Atmosphere","Atmospheric phenomena","kw_atmPhenomena_ck"],
	["Atmosphere","Atmospheric pressure","kw_atmPressure_ck"],
	["Atmosphere","Atmospheric radiation","kw_atmRadiation_ck"],
	["Atmosphere","Atmospheric temperature","kw_atmTemperature_ck"],
	["Atmosphere","Atmospheric water vapor","kw_atmVapor_ck"],
	["Atmosphere","Atmospheric winds","kw_atmWinds_ck"],
	["Atmosphere","Clouds","kw_clouds_ck"],
	["Atmosphere","Precipitation","kw_precipitation_ck"],
	["Biosphere","Aquatic ecosystems",""],
	["Biosphere","Ecological dynamics","kw_ecoDynamics_ck"],
	["Biosphere","Terrestrial ecosystems","kw_terEcosystems_ck"],
	["Biosphere","Vegetation","kw_vegetation_ck"],
	["Cryosphere","Frozen ground","kw_frozenGround_ck"],
	["Cryosphere","Glaciers / Ice sheet","kw_glaciersIcesheet_ck"],
	["Cryosphere","Sea ice","kw_seaIce_ck"],
	["Cryosphere","Snow / Ice","kw_snowIce_ck"],
	["Land Surface","Erosion / Sedimentation","kw_erosionSedimentation_ck"],
	["Land Surface","Frozen ground",""],
	["Land Surface","Geomorphology","kw_geomorphology_ck"],
	["Land Surface","Land temperature","kw_landTemperature_ck"],
	["Land Surface","Land use / Land cover","kw_landCover_ck"],
	["Land Surface","Landscape","kw_landscape_ck"],
	["Land Surface","Soils",""],
	["Land Surface","Surface radiative properties","kw_surfaceProperties_ck"],
	["Land Surface","Topography","kw_topography_ck"],
	["Ocean","Aquatic sciences",""],
	["Ocean","Bathymetry / Seafloor topography","kw_bathymetry_ck"],
	["Ocean","Coastal processes","kw_coastalProcesses_ck"],
	["Ocean","Marine environment","kw_marineEnvironment_ck"],
	["Ocean","Marine geophysics","kw_marineGeophysics_ck"],
	["Ocean","Marine sediments",""],
	["Ocean","Marine volcanisme",""],
	["Ocean","Ocean acoustics",""],
	["Ocean","Ocean chemistry",""],
	["Ocean","Ocean circulation",""],
	["Ocean","Ocean heat budget",""],
	["Ocean","Ocean optics",""],
	["Ocean","Ocean pressure",""],
	["Ocean","Ocean temperature",""],
	["Ocean","Ocean waves","kw_oceanWaves_ck"],
	["Ocean","Ocean winds","kw_oceanWinds_ck"],
	["Ocean","Salinity / Density",""],
	["Ocean","Sea ice",""],
	["Ocean","Sea surface topography","kw_seaTopography_ck"],
	["Ocean","Tides","kw_seaTides_ck"],
	["Ocean","Water quality","kw_waterQuality_ck_2"],
	["Solid Earth","Earth gases / liquides",""],
	["Solid Earth","Geochemistry",""],
	["Solid Earth","Geodetics","kw_geodetics_ck"],
	["Solid Earth","Geomagnetism","kw_geomagnetism_ck"],
	["Solid Earth","Geomorphic landforms / processes","kw_geomorphicLandforms_ck"],
	["Solid Earth","Geothermal Dynamics",""],
	["Solid Earth","Gravity / gravitational field","kw_gravity_ck"],
	["Solid Earth","Rocks / Minerals / Crystals",""],
	["Solid Earth","Tectonics",""],
	["Spectral / Engineering","Gamma ray","kw_gammaRay_ck"],
	["Spectral / Engineering","Infrared wavelengths","kw_irWavelengths_ck"],
	["Spectral / Engineering","LIDAR","kw_lidar_ck"],
	["Spectral / Engineering","Microwave","kw_microwave_ck"],
	["Spectral / Engineering","Platform characteristics",""],
	["Spectral / Engineering","RADAR","kw_radar_ck"],
	["Spectral / Engineering","Radio wave","kw_radioWave_ck"],
	["Spectral / Engineering","Sensor characteristics",""],
	["Spectral / Engineering","Ultraviolet wavelengths","kw_uvWavelentghs_ck"],
	["Spectral / Engineering","Visible wavelengths","kw_visWavelentghs_ck"],
	["Spectral / Engineering","X-ray","kw_xRay_ck"],
	["Sun-Earth Interactions","Ionosphere / Magnetosphere dynamics","kw_ionosMagnetos_ck"],
	["Sun-Earth Interactions","Solar activity","kw_solarActivity_ck"],
	["Sun-Earth Interactions","Solar energetic particle","kw_solarFlux_ck"],
	["Sun-Earth Interactions","Solar energetic particle properties","kw_solarFlux_ck"],
	["Terrestrial Hydrosphere","Glaciers / Ice sheets",""],
	["Terrestrial Hydrosphere","Ground water","kw_groundWater_ck"],
	["Terrestrial Hydrosphere","Snow / Ice",""],
	["Terrestrial Hydrosphere","Surface water","kw_surfaceWater_ck"],
	["Terrestrial Hydrosphere","Water quality / chemistry","kw_waterQuality_ck"],
	]

emc_locations = [
	["Do your choice ...",""],
	["Continents","Africa"],
	["Continents","Antarctica"],
	["Continents","Asia"],
	["Continents","Oceania"],
	["Continents","Europe"],
	["Continents","North America"],
	["Continents","South America"],
	["Countries","Afghanistan"],
	["Countries","Albania"],
	["Countries","Algeria"],
	["Countries","Amazonia"],
	["Countries","American Samoa"],
	["Countries","Amsterdam And St. Paul Islands"],
	["Countries","Andaman Islands"],
	["Countries","Andorra"],
	["Countries","Angola"],
	["Countries","Anguilla"],
	["Countries","Antigua And Barbuda"],
	["Countries","Argentina"],
	["Countries","Armenia"],
	["Countries","Aruba"],
	["Countries","Ascension Island"],
	["Countries","Australia"],
	["Countries","Austria"],
	["Countries","Azerbaijan"],
	["Countries","Bahamas"],
	["Countries","Bahrain"],
	["Countries","Baker Island"],
	["Countries","Bangladesh"],
	["Countries","Barbados"],
	["Countries","Belarus"],
	["Countries","Belgium"],
	["Countries","Belize"],
	["Countries","Benin"],
	["Countries","Bhutan"],
	["Countries","Bolivia"],
	["Countries","Bonaire"],
	["Countries","Bosnia And Herzegovina"],
	["Countries","Botswana"],
	["Countries","Bouvet Island"],
	["Countries","Brazil"],
	["Countries","British Isles"],
	["Countries","Brunei"],
	["Countries","Bulgaria"],
	["Countries","Burkina Faso"],
	["Countries","Burma"],
	["Countries","Burundi"],
	["Countries","Cambodia"],
	["Countries","Cameroon"],
	["Countries","Canada"],
	["Countries","Caribbean"],
	["Countries","Cayman Islands"],
	["Countries","Central African Republic"],
	["Countries","Ceuta"],
	["Countries","Chad"],
	["Countries","Channel Islands"],
	["Countries","Chile"],
	["Countries","China"],
	["Countries","Christmas Island"],
	["Countries","Cocos Islands"],
	["Countries","Colombia"],
	["Countries","Comoros"],
	["Countries","Congo, Democratic Republic"],
	["Countries","Congo, Republic"],
	["Countries","Cook Islands"],
	["Countries","Corsica"],
	["Countries","Costa Rica"],
	["Countries","Cote D'ivoire"],
	["Countries","Croatia"],
	["Countries","Crozet Islands"],
	["Countries","Cuba"],
	["Countries","Curacao"],
	["Countries","Cyprus"],
	["Countries","Czech Republic"],
	["Countries","Denmark"],
	["Countries","Dhekelia"],
	["Countries","Djibouti"],
	["Countries","Dominica"],
	["Countries","Dominican Republic"],
	["Countries","Ecuador"],
	["Countries","Egypt"],
	["Countries","El Salvador"],
	["Countries","Equatorial Guinea"],
	["Countries","Eritrea"],
	["Countries","Estonia"],
	["Countries","Ethiopia"],
	["Countries","Faeroe Islands"],
	["Countries","Falkland Islands"],
	["Countries","Fiji"],
	["Countries","Finland"],
	["Countries","France"],
	["Countries","French Guiana"],
	["Countries","French Polynesia"],
	["Countries","Gabon"],
	["Countries","Galapagos Islands"],
	["Countries","Gambia"],
	["Countries","Gaza Strip"],
	["Countries","Georgia, Republic"],
	["Countries","Germany"],
	["Countries","Ghana"],
	["Countries","Gibraltar"],
	["Countries","Gough Island"],
	["Countries","Greece"],
	["Countries","Greenland"],
	["Countries","Grenada"],
	["Countries","Guadeloupe"],
	["Countries","Guam"],
	["Countries","Guatemala"],
	["Countries","Guinea"],
	["Countries","Guinea-Bissau"],
	["Countries","Guyana"],
	["Countries","Haiti"],
	["Countries","Hawaii Island"],
	["Countries","Hawaiian Islands"],
	["Countries","Honduras"],
	["Countries","Hong Kong"],
	["Countries","Howland Island"],
	["Countries","Hungary"],
	["Countries","Iceland"],
	["Countries","India"],
	["Countries","Indonesia"],
	["Countries","Iran"],
	["Countries","Iraq"],
	["Countries","Ireland"],
	["Countries","Israel"],
	["Countries","Italy"],
	["Countries","Jamaica"],
	["Countries","Japan"],
	["Countries","Jarvis Island"],
	["Countries","Johnston Atoll"],
	["Countries","Jordan"],
	["Countries","Kahoolawe"],
	["Countries","Kauai"],
	["Countries","Kazakhstan"],
	["Countries","Kenya"],
	["Countries","Kerguelen Islands"],
	["Countries","Kingman Reef"],
	["Countries","Kiribati"],
	["Countries","Kosovo"],
	["Countries","Kuwait"],
	["Countries","Kyrgyzstan"],
	["Countries","Laeso"],
	["Countries","Lake Chad"],
	["Countries","Lake Malawi"],
	["Countries","Lake Tanganyika"],
	["Countries","Lake Victoria"],
	["Countries","Lanai"],
	["Countries","Laos"],
	["Countries","Latvia"],
	["Countries","Lebanon"],
	["Countries","Lesotho"],
	["Countries","Liberia"],
	["Countries","Libya"],
	["Countries","Liechtenstein"],
	["Countries","Lithuania"],
	["Countries","Luxembourg"],
	["Countries","Macau"],
	["Countries","Macedonia"],
	["Countries","Madagascar"],
	["Countries","Madeira"],
	["Countries","Malawi"],
	["Countries","Malaysia"],
	["Countries","Maldives"],
	["Countries","Mali"],
	["Countries","Malta"],
	["Countries","Marshall Islands"],
	["Countries","Martinique"],
	["Countries","Maui"],
	["Countries","Mauritania"],
	["Countries","Mauritius"],
	["Countries","Melanesia"],
	["Countries","Mexico"],
	["Countries","Micronesia"],
	["Countries","Midway Atoll"],
	["Countries","Moldova"],
	["Countries","Molokai"],
	["Countries","Monaco"],
	["Countries","Mongolia"],
	["Countries","Montenegro"],
	["Countries","Montserrat"],
	["Countries","Morocco"],
	["Countries","Mozambique"],
	["Countries","Namibia"],
	["Countries","Nauru"],
	["Countries","Navassa Island"],
	["Countries","Nepal"],
	["Countries","Netherlands Antilles"],
	["Countries","Netherlands"],
	["Countries","New Caledonia"],
	["Countries","New Zealand"],
	["Countries","Nicaragua"],
	["Countries","Nicobar Islands"],
	["Countries","Niger"],
	["Countries","Nigeria"],
	["Countries","Niihau"],
	["Countries","Niue"],
	["Countries","Norfolk Island"],
	["Countries","North Korea"],
	["Countries","Northern Mariana Islands"],
	["Countries","Norway"],
	["Countries","Oahu"],
	["Countries","Okinawa"],
	["Countries","Oman"],
	["Countries","Pakistan"],
	["Countries","Palau"],
	["Countries","Palestine"],
	["Countries","Palmyra Atoll"],
	["Countries","Panama"],
	["Countries","Papua New Guinea"],
	["Countries","Paraguay"],
	["Countries","Peru"],
	["Countries","Philippines"],
	["Countries","Pitcairn Island"],
	["Countries","Pitcairn Islands"],
	["Countries","Poland"],
	["Countries","Polynesia"],
	["Countries","Portugal"],
	["Countries","Puerto Rico"],
	["Countries","Qatar"],
	["Countries","Red Sea"],
	["Countries","Reunion"],
	["Countries","Romania"],
	["Countries","Russia"],
	["Countries","Rwanda"],
	["Countries","Saba"],
	["Countries","Sable Island"],
	["Countries","Samoa"],
	["Countries","San Marino"],
	["Countries","Sao Tome And Principe"],
	["Countries","Sardinia"],
	["Countries","Saudi Arabia"],
	["Countries","Scandinavia"],
	["Countries","Senegal"],
	["Countries","Serbia"],
	["Countries","Seychelles"],
	["Countries","Sicily"],
	["Countries","Sierra Leone"],
	["Countries","Singapore"],
	["Countries","Slovakia"],
	["Countries","Slovenia"],
	["Countries","Solomon Islands"],
	["Countries","Somalia"],
	["Countries","South Africa"],
	["Countries","South Georgia Island"],
	["Countries","South Korea"],
	["Countries","South Orkney Islands"],
	["Countries","South Sandwich Islands"],
	["Countries","Spain"],
	["Countries","Spratly Islands"],
	["Countries","Sri Lanka"],
	["Countries","St Barthelemy"],
	["Countries","St Eustatius"],
	["Countries","St Helena"],
	["Countries","St Kitts And Nevis"],
	["Countries","St Lucia"],
	["Countries","St Maarten"],
	["Countries","St Martin"],
	["Countries","St Pierre And Miquelon"],
	["Countries","St Vincent And The Grenadines"],
	["Countries","Sudan"],
	["Countries","Suriname"],
	["Countries","Svalbard And Jan Mayen"],
	["Countries","Swaziland"],
	["Countries","Sweden"],
	["Countries","Switzerland"],
	["Countries","Syria"],
	["Countries","Taiwan"],
	["Countries","Tajikistan"],
	["Countries","Tanzania"],
	["Countries","Thailand"],
	["Countries","Togo"],
	["Countries","Tokelau"],
	["Countries","Tonga"],
	["Countries","Trinidad And Tobago"],
	["Countries","Tristan Da Cunha"],
	["Countries","Tunisia"],
	["Countries","Turkey"],
	["Countries","Turkmenistan"],
	["Countries","Turks And Caicos Islands"],
	["Countries","Tuvalu"],
	["Countries","Uganda"],
	["Countries","Ukraine"],
	["Countries","United Arab Emirates"],
	["Countries","United Kingdom"],
	["Countries","United States of America"],
	["Countries","Uruguay"],
	["Countries","Uzbekistan"],
	["Countries","Vanuatu"],
	["Countries","Vatican City"],
	["Countries","Venezuela"],
	["Countries","Vietnam"],
	["Countries","Virgin Islands"],
	["Countries","Wake Island"],
	["Countries","Wallis And Futuna Islands"],
	["Countries","Yemen"],
	["Countries","Zambia"],
	["Countries","Zanzibar"],
	["Countries","Zimbabwe"],
	["Oceans","Atlantic Ocean"],
	["Oceans","Arctic Ocean"],
	["Oceans","Indian Ocean"],
	["Oceans","Pacific Ocean"],
	["Oceans","Southern Ocean"],
	["Regions","Arctic Region"],
	["Regions","Atlantic Ocean Islands"],
	["Regions","Central Africa"],
	["Regions","Central America"],
	["Regions","Central Europe"],
	["Regions","Eastern Africa"],
	["Regions","Eastern Asia"],
	["Regions","Eastern Europe"],
	["Regions","Indian Ocean Islands"],
	["Regions","Middle East"],
	["Regions","North America"],
	["Regions","Northern Africa"],
	["Regions","Northern Europe"],
	["Regions","Pacific Islands"],
	["Regions","South America"],
	["Regions","Southcentral Asia"],
	["Regions","Southern Asia"],
	["Regions","Southern Europe"],
	["Regions","Western Africa"],
	["Regions","Western Asia"],
	["Regions","Western Europe"],
	]









#window_messages = (
	#("infoButton_1","<p align=justify><u>INSPIRE:</u><br>This is a characteristic, and often a unique name identifying the resource. The value domain of this metadata element is free text.</p><u>EUFAR:</u><br>Project acronym -- survey request form.<br><br><br> ",172),
	#("infoButton_2","<p align=justify><u>INSPIRE:</u><br>This is a brief narrative summary of the content of the resource. The value domain of this metadata element is free text.</p><u>EUFAR:</u><br>Abstract -- survey request form.<br><br><br> ",172),
	#("infoButton_3","<p align=justify><u>INSPIRE:</u><br>This is the type of resource being described by the metadata. The value domain of this metadata element is defined in Part D.1.</p><u>EUFAR:</u><br>Dataset or series.<br><br><br> ",172),
	#("infoButton_4",'<p align=justify><u>INSPIRE:</u><br>The resource locator defines the link(s) to the resource and/or the link to additional information about the resource. The value domain of this metadata element is a character string, commonly expressed as uniform resource locator (URL).</p><u>EUFAR:</u><br>Link to data in EUFAR N8-DB or http://www.eufar.net.<br><br><br> ',202),
	#("infoButton_5",'<p align=justify><u>INSPIRE:</u><br>A value uniquely identifying the resource. The value domain of this metadata element is a mandatory character string code, generally assigned by the data owner, and a character string namespace uniquely identifying the context of the identifier code (for example, the data owner).</p><u>EUFAR:</u><br>N8-DB file name specification.<br><br><br> ',217),
	#("infoButton_6",'<p align=justify><u>INSPIRE:</u><br>The language(s) used within the resource. The value domain of this metadata element is limited to the languages defined in ISO 639-2.</p><u>EUFAR:</u><br>English.<br><br><br> ',172),
	#("infoButton_7",'<p align=justify><u>INSPIRE:</u><br>The topic category is a high-level classification scheme to facilitate the grouping and topic-based search of available spatial data resources. The value domain of this metadata element is defined in Part D.2.</p><u>EUFAR:</u><br>Main scientific field -- survey request form.<br><br><br> ',202),
	#("infoButton_8",'<p align=justify><u>INSPIRE:</u><br>If the keyword value originates from a controlled vocabulary (thesaurus, ontology), for example GEMET, the citation of the originating controlled vocabulary shall be provided. This citation shall include at least the title and a reference date (date of publication, date of last revision or of creation) of the originating controlled vocabulary.</p><p align=justify><u>EUFAR:</u><br>GEMET - INSPIRE themes, version 1.0, 2008-06-01.</p><br><br><br> ',232),
	#("infoButton_9",'<p align=justify><u>INSPIRE:</u><br>The keyword value is a commonly used word, formalised word or phrase used to describe the subject. While the topic category is too obscure for detailed queries, keywords can help narrowing a full text search and allow for structured keyword searches. The value domain of this metadata element is free text.</p><p align=justify><u>EUFAR:</u><br>Scientific theme -- survey request form.</p><br><br><br> ',232),
	#("infoButton_10",'<p align=justify><u>INSPIRE:</u><br>This is the extent of the resource in the geographic space, given as a bounding box. The bounding box shall be expressed with westbound and eastbound longitudes, and southbound and northbound latitudes in decimal degrees, with a precision of at least two decimals.</p><p align=justify><u>EUFAR:</u><br>Result of data processing plus information on country and region (survey request form).</p><br><br><br> ',232),
	#("infoButton_11",'<p align=justify><u>INSPIRE:</u><br>This is the name of the geographic space covered by the dataset.</p><p align=justify><u>EUFAR:</u><br>Information on country and region -- survey request form.</p><br><br><br> ',172),
	#("infoButton_12",'<p align=justify><u>INSPIRE:</u><br>This is the date of publication of the resource when available, or the date of entry into force. There may be more than one date of publication.</p><p align=justify><u>EUFAR:</u><br>Date of entry into EUFAR N8-DB.</p><br><br><br> ',172),
	#("infoButton_13",'<p align=justify><u>INSPIRE:</u><br>This is the date of last revision of the resource, in the case that the resource has been revised. There shall not be more than one date of last revision.</p><p align=justify><u>EUFAR:</u><br>Automatically created within EUFAR N8-DB (date stamp).</p><br><br><br> ',187),
	#("infoButton_14",'<p align=justify><u>INSPIRE:</u><br>This is the date of creation of the resource. There shall not be more than one date of creation.</p><p align=justify><u>EUFAR:</u><br>Date of data processing (related to product, which is stored in EUFAR N8-DB).</p><br><br><br> ',172),
	#("infoButton_15",'<p align=justify><u>INSPIRE:</u><br>The temporal extent defines the time period covered by the content of the resource. This time period may be expressed as any of the following: an individual date, an interval of dates expressed represented by the starting date and end date of the interval, or a mix of individual dates and intervals of dates.</p><p align=justify><u>EUFAR:</u><br>Date of data acquisition.</p><br><br><br> ',217),
	#("infoButton_16",'<p align=justify><u>INSPIRE:</u><br>This is a statement on process history and/or overall quality of the spatial data set. Where appropriate, it may include a statement on whether the data set has been validated or its quality assured, it is the official version (if multiple versions exist), and it has legal validity. The value domain of this metadata element is free text.</p><p align=justify><u>EUFAR:</u><br>Result of data processing including processing level, date and time of processing.</p><br><br><br> ',247),
	#("infoButton_17",'<p align=justify><u>INSPIRE:</u><br>Spatial resolution refers to the level of detail of the data set. It shall be expressed as a set of zero up to many resolution distances (typically for gridded data and imagery-derived products) or equivalent scales (typically for maps or map-derived products). An equivalent scale is generally expressed as an integer value expressing the scale denominator. A resolution distance shall be expressed as a numerical value associated with a unit of length.</p><p align=justify><u>EUFAR:</u><br>Result of data processing.</p><br><br><br> ',262),
	#("infoButton_18",'<p align=justify><u>INSPIRE:</u><br>This is a citation of the implementing rules adopted under Article 7(1) of Directive 2007/2/EC or other specification to which a particular resource conforms. A resource may conform to more than one implementing rules adopted under Article 7(1) of Directive 2007/2/EC or other specification. This citation shall include at least the title and a reference date (date of publication, date of last revision or of creation) of the implementing rules adopted under Article 7(1) of Directive 2007/2/EC or of the specification.</p><p align=justify><u>EUFAR:</u><br>Not evaluated.</p><br><br><br> ',292),
	#("infoButton_21",'<p align=justify><u>INSPIRE:</u><br>This is the degree of conformity of the resource to the implementing rules adopted under Article 7(1) of Directive 2007/2/EC or other specification. The value domain of this metadata element is defined in Part D.</p><p align=justify><u>EUFAR:</u><br>True.</p><br><br><br> ',197),
	#("infoButton_22",'<p align=justify><u>INSPIRE:</u><br>This metadata element defines the conditions for access and use of spatial data sets and services, and where applicable, corresponding fees as required by Article 5(2)(b) and Article 11(2)(f) of Directive 2007/2/EC. The value domain of this metadata element is free text. The element must have values. If no conditions apply to the access and use of the resource, "no conditions apply" shall be used. If conditions are unknown, "conditions unknown" shall be used. This element shall also provide information on any fees necessary to access and use the resource, if applicable, or refer to a uniform resource locator (URL) where information on fees is available.</p><p align=justify><u>EUFAR:</u><br>Consortium agreement for access usage restrictions.</p><br><br><br> ',322),
	#("infoButton_23",'<p align=justify><u>INSPIRE:</u><br>When Member States limit public access to spatial data sets and spatial data services under Article 13 of Directive 2007/2/EC, the metadata element shall provide information on the limitations and the reasons for this. If there are no limitations on public access, the metadata element shall indicate this. The value domain of the metadata element is free text.</p><p align=justify><u>EUFAR:</u><br>Consortium agreement for public access limitations.</p><br><br><br> ',247),
	#("infoButton_24",'<p align=justify><u>INSPIRE:</u><br>This is the description of the organisation responsible for the establishment, management, maintenance and distribution of the resource. This description shall include:<ul><li>the name of the organisation as free text</li><li>a contact e-mail address as a character string</li></ul><p align=justify><u>EUFAR:</u><br>Party, who created the resource/data provider.</p><br><br><br> ',232),
	#("infoButton_25",'<p align=justify><u>INSPIRE:</u><br>This is the description of the organisation responsible for the establishment, management, maintenance and distribution of the resource. This description shall include:<ul><li>the name of the organisation as free text</li><li>a contact e-mail address as a character string</li></ul><p align=justify><u>EUFAR:</u><br>Party, who created the resource/data provider.</p><br><br><br> ',232),
	#("infoButton_26",'<p align=justify><u>INSPIRE:</u><br>This is the role of the responsible organisation. The value domain of this metadata element is defined in Part D.</p><p align=justify><u>EUFAR:</u><br>pointOfContact and principalInvestigator (two different entries).</p><br><br><br> ',187),
	#("infoButton_27",'<p align=justify><u>INSPIRE:</u><br>The date which specifies when the metadata record was created or updated. This date shall be expressed in conformity with ISO 8601.</p><p align=justify><u>EUFAR:</u><br>Date when the metadata record was created or updated (result of data processing or entry into DB).</p><br><br><br> ',187),
	#("infoButton_28",'<p align=justify><u>INSPIRE:</u><br>This is the language in which the metadata elements are expressed. The value domain of this metadata element is limited to the official languages of the Community and is expressed in conformity with ISO 639-2.</p><p align=justify><u>EUFAR:</u><br>English.</p><br><br><br> ',187),
	#("infoButton_29",'<p align=justify><u>INSPIRE & EUFAR:</u><br>This is the name and the contact e-mail of the party responsible for the data set.</p><br><br><br> ',112),
	#("infoButton_33",'<p align=justify><u>EUFAR:</u><br>This is the aircraft used to acquire the actual data and metadata.</p><br><br><br> ',117),
	#("infoButton_34",'<p align=justify><u>EUFAR:</u><br>This(these) is(are) the instrument(s) used to acquire the actual data and metadata.</p><br><br><br> ',117),
	#)


window_messages = (
	("infoButton_1","<p align=justify><u>INSPIRE:</u><br>This is a characteristic, and often a unique name identifying the resource. The value domain of this metadata element is free text.</p><u>EUFAR:</u><br>Project acronym -- survey request form."),
	("infoButton_2","<p align=justify><u>INSPIRE:</u><br>This is a brief narrative summary of the content of the resource. The value domain of this metadata element is free text.</p><u>EUFAR:</u><br>Abstract -- survey request form."),
	("infoButton_3","<p align=justify><u>INSPIRE:</u><br>This is the type of resource being described by the metadata. The value domain of this metadata element is defined in Part D.1.</p><u>EUFAR:</u><br>Dataset or series."),
	("infoButton_4",'<p align=justify><u>INSPIRE:</u><br>The resource locator defines the link(s) to the resource and/or the link to additional information about the resource. The value domain of this metadata element is a character string, commonly expressed as uniform resource locator (URL).</p><u>EUFAR:</u><br>Link to data in EUFAR N8-DB or http://www.eufar.net.'),
	("infoButton_5",'<p align=justify><u>INSPIRE:</u><br>A value uniquely identifying the resource. The value domain of this metadata element is a mandatory character string code, generally assigned by the data owner, and a character string namespace uniquely identifying the context of the identifier code (for example, the data owner).</p><u>EUFAR:</u><br>N8-DB file name specification.'),
	("infoButton_6",'<p align=justify><u>INSPIRE:</u><br>The language(s) used within the resource. The value domain of this metadata element is limited to the languages defined in ISO 639-2.</p><u>EUFAR:</u><br>English.'),
	("infoButton_7",'<p align=justify><u>INSPIRE:</u><br>The topic category is a high-level classification scheme to facilitate the grouping and topic-based search of available spatial data resources. The value domain of this metadata element is defined in Part D.2.</p><u>EUFAR:</u><br>Main scientific field -- survey request form.'),
	("infoButton_8",'<p align=justify><u>INSPIRE:</u><br>If the keyword value originates from a controlled vocabulary (thesaurus, ontology), for example GEMET, the citation of the originating controlled vocabulary shall be provided. This citation shall include at least the title and a reference date (date of publication, date of last revision or of creation) of the originating controlled vocabulary.</p><p align=justify><u>EUFAR:</u><br>GEMET - INSPIRE themes, version 1.0, 2008-06-01.</p>'),
	("infoButton_9",'<p align=justify><u>INSPIRE:</u><br>The keyword value is a commonly used word, formalised word or phrase used to describe the subject. While the topic category is too obscure for detailed queries, keywords can help narrowing a full text search and allow for structured keyword searches. The value domain of this metadata element is free text.</p><p align=justify><u>EUFAR:</u><br>Keywords are from NASA/Global Change Master Directory (GCMD) Earth Science Keywords.</p>'),
	("infoButton_10",'<p align=justify><u>INSPIRE:</u><br>This is the extent of the resource in the geographic space, given as a bounding box. The bounding box shall be expressed with westbound and eastbound longitudes, and southbound and northbound latitudes in decimal degrees, with a precision of at least two decimals.</p><p align=justify><u>EUFAR:</u><br>Result of data processing plus information on country and region (survey request form).</p>'),
	("infoButton_11",'<p align=justify><u>INSPIRE:</u><br>This is the name of the geographic space covered by the dataset.</p><p align=justify><u>EUFAR:</u><br>Information on country and region -- survey request form.</p>'),
	("infoButton_12",'<p align=justify><u>INSPIRE:</u><br>This is the date of publication of the resource when available, or the date of entry into force. There may be more than one date of publication.</p><p align=justify><u>EUFAR:</u><br>Date of entry into EUFAR N8-DB.</p>'),
	("infoButton_13",'<p align=justify><u>INSPIRE:</u><br>This is the date of last revision of the resource, in the case that the resource has been revised. There shall not be more than one date of last revision.</p><p align=justify><u>EUFAR:</u><br>Automatically created within EUFAR N8-DB (date stamp).</p>'),
	("infoButton_14",'<p align=justify><u>INSPIRE:</u><br>This is the date of creation of the resource. There shall not be more than one date of creation.</p><p align=justify><u>EUFAR:</u><br>Date of data processing (related to product, which is stored in EUFAR N8-DB).</p>'),
	("infoButton_15",'<p align=justify><u>INSPIRE:</u><br>The temporal extent defines the time period covered by the content of the resource. This time period may be expressed as any of the following: an individual date, an interval of dates expressed represented by the starting date and end date of the interval, or a mix of individual dates and intervals of dates.</p><p align=justify><u>EUFAR:</u><br>Date of data acquisition.</p>'),
	("infoButton_16",'<p align=justify><u>INSPIRE:</u><br>This is a statement on process history and/or overall quality of the spatial data set. Where appropriate, it may include a statement on whether the data set has been validated or its quality assured, it is the official version (if multiple versions exist), and it has legal validity. The value domain of this metadata element is free text.</p><p align=justify><u>EUFAR:</u><br>Result of data processing including processing level, date and time of processing.</p>'),
	("infoButton_17",'<p align=justify><u>INSPIRE:</u><br>Spatial resolution refers to the level of detail of the data set. It shall be expressed as a set of zero up to many resolution distances (typically for gridded data and imagery-derived products) or equivalent scales (typically for maps or map-derived products). An equivalent scale is generally expressed as an integer value expressing the scale denominator. A resolution distance shall be expressed as a numerical value associated with a unit of length.</p><p align=justify><u>EUFAR:</u><br>Result of data processing.</p>'),
	("infoButton_18",'<p align=justify><u>INSPIRE:</u><br>This is a citation of the implementing rules adopted under Article 7(1) of Directive 2007/2/EC or other specification to which a particular resource conforms. A resource may conform to more than one implementing rules adopted under Article 7(1) of Directive 2007/2/EC or other specification. This citation shall include at least the title and a reference date (date of publication, date of last revision or of creation) of the implementing rules adopted under Article 7(1) of Directive 2007/2/EC or of the specification.</p><p align=justify><u>EUFAR:</u><br>Not evaluated.</p>'),
	("infoButton_21",'<p align=justify><u>INSPIRE:</u><br>This is the degree of conformity of the resource to the implementing rules adopted under Article 7(1) of Directive 2007/2/EC or other specification. The value domain of this metadata element is defined in Part D.</p><p align=justify><u>EUFAR:</u><br>True.</p>'),
	("infoButton_22",'<p align=justify><u>INSPIRE:</u><br>This metadata element defines the conditions for access and use of spatial data sets and services, and where applicable, corresponding fees as required by Article 5(2)(b) and Article 11(2)(f) of Directive 2007/2/EC. The value domain of this metadata element is free text. The element must have values. If no conditions apply to the access and use of the resource, "no conditions apply" shall be used. If conditions are unknown, "conditions unknown" shall be used. This element shall also provide information on any fees necessary to access and use the resource, if applicable, or refer to a uniform resource locator (URL) where information on fees is available.</p><p align=justify><u>EUFAR:</u><br>Consortium agreement for access usage restrictions.</p>'),
	("infoButton_23",'<p align=justify><u>INSPIRE:</u><br>When Member States limit public access to spatial data sets and spatial data services under Article 13 of Directive 2007/2/EC, the metadata element shall provide information on the limitations and the reasons for this. If there are no limitations on public access, the metadata element shall indicate this. The value domain of the metadata element is free text.</p><p align=justify><u>EUFAR:</u><br>Consortium agreement for public access limitations.</p>'),
	("infoButton_24",'<p align=justify><u>INSPIRE:</u><br>This is the description of the organisation responsible for the establishment, management, maintenance and distribution of the resource. This description shall include:<ul><li>the name of the organisation as free text</li><li>a contact e-mail address as a character string</li></ul><p align=justify><u>EUFAR:</u><br>Party, who created the resource/data provider.</p>'),
	("infoButton_25",'<p align=justify><u>INSPIRE:</u><br>This is the description of the organisation responsible for the establishment, management, maintenance and distribution of the resource. This description shall include:<ul><li>the name of the organisation as free text</li><li>a contact e-mail address as a character string</li></ul><p align=justify><u>EUFAR:</u><br>Party, who created the resource/data provider.</p>'),
	("infoButton_26",'<p align=justify><u>INSPIRE:</u><br>This is the role of the responsible organisation. The value domain of this metadata element is defined in Part D.</p><p align=justify><u>EUFAR:</u><br>pointOfContact and principalInvestigator (two different entries).</p>'),
	("infoButton_27",'<p align=justify><u>INSPIRE:</u><br>The date which specifies when the metadata record was created or updated. This date shall be expressed in conformity with ISO 8601.</p><p align=justify><u>EUFAR:</u><br>Date when the metadata record was created or updated (result of data processing or entry into DB).</p>'),
	("infoButton_28",'<p align=justify><u>INSPIRE:</u><br>This is the language in which the metadata elements are expressed. The value domain of this metadata element is limited to the official languages of the Community and is expressed in conformity with ISO 639-2.</p><p align=justify><u>EUFAR:</u><br>English.</p>'),
	("infoButton_29",'<p align=justify><u>INSPIRE & EUFAR:</u><br>This is the name and the contact e-mail of the party responsible for the data set.</p>'),
	("infoButton_30",'<p align=justify><u>INSPIRE & EUFAR:</u><br>Spatial resolution refers to the level of detail of the data set. It shall be expressed as a set of zero to many resolution distances (typically for gridded data and imagery-derived products) or equivalent scales (typically for maps or map-derived products). An equivalent scale is generally expressed as an integer value expressing the scale denominator. A resolution distance shall be expressed as a numerical value associated with a unit of length.</p>'),
	("infoButton_33",'<p align=justify><u>EUFAR:</u><br>This is the aircraft used to acquire the actual data and metadata.</p>'),
	("infoButton_34",'<p align=justify><u>EUFAR:</u><br>This(these) is(are) the instrument(s) used to acquire the actual data and metadata.</p>'),
	)



intruments_information = [
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Aerosol Monitors","AARP","University of Manchester"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Aerosol Monitors","CAPS","Droplet Measurement Technologies"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Aerosol Monitors","CAS Spectrometer","Baumgardner et al., 2001"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Aerosol Monitors","Cloud Imaging Probe","Not specified"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Aerosol Monitors","LASAIR-5295","Particle Measurement Systems"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Aerosol Monitors","PCASP-100X","Droplet Measurement Technologies"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Aerosol Monitors","PCASP-SPP200","Droplet Measurement Technologies"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Aerosol Monitors","SPEC Hawkeye","Stratton Park Engineering Company"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Aerosol Monitors","UHSAS-A","Droplet Measurement Technologies"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Aerosol Monitors","VACC","University of Leeds"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Aethalometers","AE-42","Magee Scientific"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Aethalometers","AE-52 Aethelometer","Magee Scientific"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Aethalometers","PSAP","Radiance Research Inc."],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Carbon Analyzers","AL5002","Aero-Laser Gmbh"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Carbon Analyzers","AL5003","Aero-Laser Gmbh"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Carbon Analyzers","SP-2","Droplet Measurement Technologies"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Carbon, Hydrogen, Nitrogen Analyzers","CW-QCLAS","Aerodyne Research Inc."],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Condensation Nuclei Counter","CCN Counter","Droplet Measurement Technologies"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Condensation Nuclei Counter","COPAS","University of Mainz"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Condensation Nuclei Counter","CPI","Stratton Park Engineering Company"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Condensation Nuclei Counter","SMPS","Grimm Technologies Inc."],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Condensation Nuclei Counter","TSI-3007","TSI Inc."],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Condensation Nuclei Counter","TSI-3010","TSI Inc."],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Condensation Nuclei Counter","TSI-3022","TSI Inc."],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Condensation Nuclei Counter","TSI-3025","TSI Inc."],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Condensation Nuclei Counter","TSI-3776","TSI Inc."],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Condensation Nuclei Counter","TSI-3786","TSI Inc."],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Fluorometers","HALOX","Forschungszentrum Julich GmbH"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Flurorescence Spectroscopy","FAGE","University of Leeds"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Gas Chromatographs","HAGAR","University of Frankfurt"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Gas Chromatographs","PAN GC","Ai Qualitek Ltd"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Gas Chromatographs","VOC GC","Airmotec AG"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Gas Sensors","Formaldehyde Detectors","Others"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Gas Sensors","IR Gas analyzer","Edinburgh Sensors"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Gas Sensors","LGR 907","Los Gatos Research Inc."],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Gas Sensors","LGR DLT100","Los Gatos Research Inc."],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Gas Sensors","LI-COR 6262","LI-COR"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Gas Sensors","LI-COR 7500","LI-COR"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Gas Sensors","ORAC","University of Leeds"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Gas Sensors","PERCA","University of Leceister"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Gas Sensors","Peroxide Detectors","Others"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Nondispersive Infrared Gas Analyzers","S-5002","Sistemas Instalaciones Redes S.A."],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Nondispersive Infrared Gas Analyzers","S-5006","Sistemas Instalaciones Redes S.A."],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Nondispersive Infrared Gas Analyzers","S-5012","Sistemas Instalaciones Redes S.A."],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Ozone Monitors","Ozone Monitor 202","2B Technologies"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Ozone Monitors","Ozone Monitor","2B Technologies"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Ozone Monitors","PSI-O3","Paul Scherrer Institut"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Ozone Monitors","SA 41M","Environment S.A."],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Ozone Monitors","TECO 42C","ThermoScientific"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Ozone Monitors","TECO 42S","ThermoScientific"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Ozone Monitors","TECO 48CS","ThermoScientific"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Ozone Monitors","TECO 49PS","ThermoScientific"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Ozone Monitors","TECO 49S","ThermoScientific"],
	["In Situ/Laboratory Instruments","Current/Wind Meters","Counterflow Virtual Impactors","Counterflow Virtual Impactor","Met Office"],
	["In Situ/Laboratory Instruments","Current/Wind Meters","Wind Monitors","5-hole Turbulence Probe","DLR"],
	["In Situ/Laboratory Instruments","Current/Wind Meters","Wind Monitors","5-hole Turbulence Probe","FAAM"],
	["In Situ/Laboratory Instruments","Current/Wind Meters","Wind Monitors","5-hole Turbulence Probe","MetAir AG"],
	["In Situ/Laboratory Instruments","Current/Wind Meters","Wind Monitors","5-hole Turbulence Probe","SAFIRE"],
	["In Situ/Laboratory Instruments","Current/Wind Meters","Wind Monitors","858AJ28","Rosemount"],
	["In Situ/Laboratory Instruments","Current/Wind Meters","Wind Monitors","AIMMS-20","Aventech Inc."],
	["In Situ/Laboratory Instruments","Current/Wind Meters","Wind Monitors","Aircraft Systems","Others"],
	["In Situ/Laboratory Instruments","Current/Wind Meters","Wind Monitors","BAT","NOAA / Airborne Research Australia"],
	["In Situ/Laboratory Instruments","Current/Wind Meters","Wind Monitors","Mobile Flux Platform","IBIMET CNR"],
	["In Situ/Laboratory Instruments","Current/Wind Meters","Wind Monitors","Others","Others"],
	["In Situ/Laboratory Instruments","Current/Wind Meters","Wind Monitors","Solent HS","Gill Instruments Ltd"],
	["In Situ/Laboratory Instruments","Current/Wind Meters","Wind Monitors","Solent HS-100","Gill Instruments Ltd"],
	["In Situ/Laboratory Instruments","Current/Wind Meters","Wind Monitors","Solent HS-50","Gill Instruments Ltd"],
	["In Situ/Laboratory Instruments","Magnetic/Motion Sensors","Accelerometers","3150","ICSensors / Measurement Specialties"],
	["In Situ/Laboratory Instruments","Magnetic/Motion Sensors","Accelerometers","Aircraft Systems","Others"],
	["In Situ/Laboratory Instruments","Magnetic/Motion Sensors","Accelerometers","Kistler 3 axes accelerometers","Kistler Instrumente AG"],
	["In Situ/Laboratory Instruments","Magnetic/Motion Sensors","Accelerometers","Others","Others"],
	["In Situ/Laboratory Instruments","Magnetic/Motion Sensors","Accelerometers","SFIM 3 axes accelerometers","SFIM"],
	["In Situ/Laboratory Instruments","Magnetic/Motion Sensors","Accelerometers","Sundstrand 3 axes accelerometers","Sundstrand"],
	["In Situ/Laboratory Instruments","Magnetic/Motion Sensors","Gravimeters","S56","Micro-g LaCoste"],
	["In Situ/Laboratory Instruments","Photon/Optical Detectors","Optical Particle Counters","1.108","Grimm Technologies Inc."],  # Livre Jean Louis
	["In Situ/Laboratory Instruments","Photon/Optical Detectors","Optical Particle Counters","1.109","Grimm Technologies Inc."],  # Livre Jean Louis
	["In Situ/Laboratory Instruments","Photon/Optical Detectors","Optical Particle Counters","R4903","Met One Instruments"],  # Livre Jean Louis
	["In Situ/Laboratory Instruments","Photon/Optical Detectors","Optical Particle Counters","SID-2","University of Hertfordshire"],  # Livre Jean Louis
	["In Situ/Laboratory Instruments","Photon/Optical Detectors","Tunable Diode Lasers","TDLAS","Imperial College London"],
	["In Situ/Laboratory Instruments","Photon/Optical Detectors","Tunable Diode Lasers","TDLAS","National Physical Laboratory"],
	["In Situ/Laboratory Instruments","Photon/Optical Detectors","Tunable Diode Lasers","WVSS-II","SpectraSensors Inc."],
	["In Situ/Laboratory Instruments","Pressure/Height Meters","Pitot-static Systems","Pitot Probe","Others"],
	["In Situ/Laboratory Instruments","Pressure/Height Meters","Pressure Sensors","1201","Rosemount"],
	["In Situ/Laboratory Instruments","Pressure/Height Meters","Pressure Sensors","1221","Rosemount"],
	["In Situ/Laboratory Instruments","Pressure/Height Meters","Pressure Sensors","Aircraft Systems","Others"],
	["In Situ/Laboratory Instruments","Pressure/Height Meters","Pressure Sensors","Aircraft Systems","Others"],
	["In Situ/Laboratory Instruments","Pressure/Height Meters","Pressure Sensors","B270","Setra Systems"],
	["In Situ/Laboratory Instruments","Pressure/Height Meters","Pressure Sensors","Others","Others"],
	["In Situ/Laboratory Instruments","Pressure/Height Meters","Pressure Sensors","Others","Others"],
	["In Situ/Laboratory Instruments","Pressure/Height Meters","Pressure Sensors","UMP40","Sextant"],
	["In Situ/Laboratory Instruments","Probes","Cloud Droplet Probes","ADA-100-PDPA","TSI Inc."],
	["In Situ/Laboratory Instruments","Probes","Cloud Liquid Water Probes","BCP","Droplet Measurement Technologies"],
	["In Situ/Laboratory Instruments","Probes","Cloud Liquid Water Probes","CDP-2","Droplet Measurement Technologies"],
	["In Situ/Laboratory Instruments","Probes","Cloud Liquid Water Probes","CIP","Droplet Measurement Technologies"],
	["In Situ/Laboratory Instruments","Probes","Cloud Liquid Water Probes","CIP-100","Droplet Measurement Technologies"],
	["In Situ/Laboratory Instruments","Probes","Cloud Liquid Water Probes","CIP-15","Droplet Measurement Technologies"],
	["In Situ/Laboratory Instruments","Probes","Cloud Liquid Water Probes","FSSP-100","Particle Measuring Systems"],
	["In Situ/Laboratory Instruments","Probes","Cloud Liquid Water Probes","FSSP-100ER","Particle Measuring Systems"],
	["In Situ/Laboratory Instruments","Probes","Cloud Liquid Water Probes","FSSP-300","Particle Measuring Systems"],
	["In Situ/Laboratory Instruments","Probes","Cloud Liquid Water Probes","HVPS","Stratton Park Engineering Company"],
	["In Situ/Laboratory Instruments","Probes","Cloud Liquid Water Probes","King Probe","Particle Measuring Systems"],
	["In Situ/Laboratory Instruments","Probes","Cloud Liquid Water Probes","PVM-100","Gerber Scientific Inc."],
	["In Situ/Laboratory Instruments","Probes","Nevzorov Probes","Nevzorov IVO-2a","Sky Tech Research Inc."],
	["In Situ/Laboratory Instruments","Probes","Nevzorov Probes","Nevzorov","Sky Tech Research Inc."],
	["In Situ/Laboratory Instruments","Radiation Sensors","Quantum Sensors","LI-COR Quantum Sensor","LI-COR"],
	["In Situ/Laboratory Instruments","Recorders/Loggers","Automated Weather Systems","Meteorological Sensor Package","DLR"],
	["In Situ/Laboratory Instruments","Recorders/Loggers","Inertial Measurement Units","AIRINS","iXBlue"], #A CORRIGER !!
	["In Situ/Laboratory Instruments","Recorders/Loggers","Inertial Measurement Units","Aircraft Systems","Others"], #A CORRIGER !!
	["In Situ/Laboratory Instruments","Recorders/Loggers","Inertial Measurement Units","CCNS4","IGI mbH"], #A CORRIGER !!
	["In Situ/Laboratory Instruments","Recorders/Loggers","Inertial Measurement Units","High Accuracy INS","SAGEM"], #A CORRIGER !!
	["In Situ/Laboratory Instruments","Recorders/Loggers","Inertial Measurement Units","LTN 90-100","Litton"], #A CORRIGER !!
	["In Situ/Laboratory Instruments","Recorders/Loggers","Inertial Measurement Units","Lasernav YG1761B","Honeywell"], #A CORRIGER !!
	["In Situ/Laboratory Instruments","Recorders/Loggers","Inertial Measurement Units","Others","Others"], #A CORRIGER !!
	["In Situ/Laboratory Instruments","Recorders/Loggers","Inertial Measurement Units","POS AV 510","Applanix"], #A CORRIGER !!
	["In Situ/Laboratory Instruments","Recorders/Loggers","Inertial Measurement Units","POSAV-410","Applanix"], #A CORRIGER !!
	["In Situ/Laboratory Instruments","Recorders/Loggers","Inertial Measurement Units","RT3102","Oxford Technical Solutions"], #A CORRIGER !!
	["In Situ/Laboratory Instruments","Recorders/Loggers","Inertial Measurement Units","ULISS 45i","SAGEM"], #A CORRIGER !!
	["In Situ/Laboratory Instruments","Samplers","Bottles/Flasks/Jars","Flask Array Sampler","Atmospheric Observing Systems Inc."],
	["In Situ/Laboratory Instruments","Samplers","Bottles/Flasks/Jars","Flask Sampling System","MetAir"],
	["In Situ/Laboratory Instruments","Samplers","Grabbers/Traps/Collectors","Filter Sampler","Others"],
	["In Situ/Laboratory Instruments","Samplers","Grabbers/Traps/Collectors","Whole Air Sampling System","University of York"],
	["In Situ/Laboratory Instruments","Spectrometers/Radiometers","Chemiluminescence","MetAir NOxTOy","MetAir AG"],
	["In Situ/Laboratory Instruments","Spectrometers/Radiometers","Chemiluminescence","NO CLD","DLR"],
	["In Situ/Laboratory Instruments","Spectrometers/Radiometers","Chemiluminescence","SIOUX","DLR"],
	["In Situ/Laboratory Instruments","Spectrometers/Radiometers","Chemiluminescence","TECO 42C","ThermoScientific"],
	["In Situ/Laboratory Instruments","Spectrometers/Radiometers","Chemiluminescence","TECO 43C","ThermoScientific"],
	["In Situ/Laboratory Instruments","Spectrometers/Radiometers","Chemiluminescence","TECO 48","ThermoScientific"],
	["In Situ/Laboratory Instruments","Spectrometers/Radiometers","Mass Spectrometers","PTR-MS","University of East Anglia"],
	["In Situ/Laboratory Instruments","Spectrometers/Radiometers","Mass Spectrometers","TOF-AMS","Aerodyne Research Inc."],
	["In Situ/Laboratory Instruments","Spectrometers/Radiometers","Radiometers","Campbell Q7.1","Campbell Scientific"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Hygrometers","1011C","Buck Research Instruments L.L.C."],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Hygrometers","Aircraft systems","Others"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Hygrometers","CR-1","Buck Research Instruments L.L.C."],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Hygrometers","CR-2","Buck Research Instruments L.L.C."],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Hygrometers","Dewtrak-137","EdgeTech Instruments"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Hygrometers","Dewtrak-200","EdgeTech Instruments"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Hygrometers","FS2 Relative Humidity","Aerodata GmbH"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Hygrometers","Flourescence Water Vapour Sensor","Met Office"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Hygrometers","GE-1011B","General Eastern"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Hygrometers","GE-1011C","General Eastern"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Hygrometers","HMP","Vaisala / Rosemount"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Hygrometers","HMP233","Vaisala"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Hygrometers","S3000","Michell Instruments GmbH"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Hygrometers","TP3-S","Meteolabor AG"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Hygrometers","Total Water Content","Met Office"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Lyman-Alpha Hygrometers","Lyman-alpha HMS-2","Buck Research Instruments L.L.C."],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Lyman-Alpha Hygrometers","Lyman-alpha L-5","Buck Research Instruments L.L.C."],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Temperature Sensors","PT","Rosemount"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Temperature Sensors","PT100","Rosemount"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Temperature Sensors","PT102AL","Rosemount"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Temperature Sensors","PT102BL","Rosemount"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Temperature Sensors","PT102BW","Rosemount"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Temperature Sensors","PT102DB1 AG","Rosemount"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Temperature Sensors","PT102E2 AL","Rosemount"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Temperature Sensors","PT102E4 AL","Rosemount"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Temperature Sensors","PT50","Rosemount"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Temperature Sensors","PT500","Rosemount"],
	["Remote Sensing Instruments","Altimeters","Lidar/Laser Altimeters","ALS50","Leica Geosystems"],
	["Remote Sensing Instruments","Altimeters","Lidar/Laser Altimeters","LD90","Riegl Laser Measurement Systems GmbH"],
	["Remote Sensing Instruments","Altimeters","Lidar/Laser Altimeters","LMS-Q280","Riegl Laser Measurement Systems GmbH"],
	["Remote Sensing Instruments","Altimeters","Lidar/Laser Altimeters","LMS-Q560","Riegl Laser Measurement Systems GmbH"],
	["Remote Sensing Instruments","Altimeters","Lidar/Laser Altimeters","LMS-Q680i","Riegl Laser Measurement Systems GmbH"],
	["Remote Sensing Instruments","Altimeters","Lidar/Laser Altimeters","ULS","Laser Technology Inc."],
	["Remote Sensing Instruments","Altimeters","Radar Altimeters","AA-300","Sperry"],
	["Remote Sensing Instruments","Altimeters","Radar Altimeters","AHV16","Thales"],
	["Remote Sensing Instruments","Altimeters","Radar Altimeters","AHV8","TRT"],
	["Remote Sensing Instruments","Altimeters","Radar Altimeters","Aircraft Systems","Others"],
	["Remote Sensing Instruments","Altimeters","Radar Altimeters","KA-131","Bendix King"],
	["Remote Sensing Instruments","Imaging Radars","Imaging Radar Systems","Aircraft Systems","Others"],
	["Remote Sensing Instruments","Imaging Radars","Imaging Radar Systems","RALI","LATMOS"],
	["Remote Sensing Instruments","Imaging Radars","Imaging Radar Systems","RDR-4B","Honeywell"],
	["Remote Sensing Instruments","Imaging Radars","Imaging Radar Systems","Radar Echo Sounding System","AWI"],
	["Remote Sensing Instruments","Imaging Radars","Synthetic Aperture Radars","E-SAR","DLR"],
	["Remote Sensing Instruments","Imaging Radars","Synthetic Aperture Radars","F-SAR","DLR"],
	["Remote Sensing Instruments","Magnetic Field/Electric Field Instruments","Magnetometers","AADC II","Scintrex Ltd"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Cameras","IS-2","Interspect Ltd."],
	["Remote Sensing Instruments","Photon/Optical Detectors","Cameras","RCD105","Leica-Geosystems"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Cameras","RMK A 30/23","Zeiss"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Cameras","RMK A","Zeiss"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Ice Particle Analyzers","CEV","INTA"], # A VERIFIER
	["Remote Sensing Instruments","Photon/Optical Detectors","Ice Particle Analyzers","Ice Nucleus Counter","University of Manchester"], # A VERIFIER
	["Remote Sensing Instruments","Photon/Optical Detectors","Infrared Cameras","FLIR M40","FLIR Systems Inc."], # A VERIFIER
	["Remote Sensing Instruments","Photon/Optical Detectors","Infrared Cameras","FLIR SC3000","FLIR Systems Inc."], # A VERIFIER
	["Remote Sensing Instruments","Photon/Optical Detectors","Infrared Cameras","IRCAM","Jenoptik AG"], # A VERIFIER
	["Remote Sensing Instruments","Photon/Optical Detectors","Multispectral Cameras","IS2+","Interspect Ltd."],
	["Remote Sensing Instruments","Photon/Optical Detectors","Multispectral Cameras","MS4100","Duncantech"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Nephelometers","Airborne Visibility Meter","HSS Inc."],
	["Remote Sensing Instruments","Photon/Optical Detectors","Nephelometers","RR-0150","RadianceResearch"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Nephelometers","TSI-3563","TSI Inc."],
	["Remote Sensing Instruments","Photon/Optical Detectors","Photometers","JO1D / JNO2 Photometer","Unknown"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Video Cameras","GR-DV400","JVC"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Video Cameras","HRSC AX","DLR"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Video Cameras","IS-3","Interspect"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Video Cameras","IS-4","Interspect"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Video Cameras","LTC 0600","Philipps"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Video Cameras","Sony Video Camera","Sony"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Video Cameras","Video Camera","Others"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Video Cameras","dIGIcam K14","IGI mbH"],
	["Remote Sensing Instruments","Positioning/Navigation","Ground Positioning Systems","AT4","Javad GNSS Inc."],
	["Remote Sensing Instruments","Positioning/Navigation","Ground Positioning Systems","Aircraft systems","Others"],
	["Remote Sensing Instruments","Positioning/Navigation","Ground Positioning Systems","Garmin GPS","Garmin"],
	["Remote Sensing Instruments","Positioning/Navigation","Ground Positioning Systems","Gyro-4","Javad GNSS Inc."],
	["Remote Sensing Instruments","Positioning/Navigation","Ground Positioning Systems","OEM4-G2","NovAtel Inc."],
	["Remote Sensing Instruments","Positioning/Navigation","Ground Positioning Systems","Others","Others"],
	["Remote Sensing Instruments","Positioning/Navigation","Ground Positioning Systems","Trimble 2101","Trimble Navigation"],
	["Remote Sensing Instruments","Positioning/Navigation","Ground Positioning Systems","Trimble 4000 SSI","Trimble Navigation"],
	["Remote Sensing Instruments","Positioning/Navigation","Ground Positioning Systems","Trimble TNL 2000","Trimble Navigation"],
	["Remote Sensing Instruments","Positioning/Navigation","Ground Positioning Systems","XR5","Navstar Electronics"],
	["Remote Sensing Instruments","Profilers/Sounders","Dropsondes","AVAPS","Vaisala"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Cloud, Aerosol, Precipitation Spectrometers","CAPS - LWC","Droplet Measurement Technologies"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Cloud, Aerosol, Precipitation Spectrometers","J-W LWC","Johnson-Williams"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Fourier Transform Infrared Spectrometers"," ARIES","Met Office / ABB Bomem"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Fourier Transform Infrared Spectrometers","CRISTA New Frontiers","ForschungsZentrum Juelich"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Fourier Transform Infrared Spectrometers","FTIR","Midac Inc."],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Fourier Transform Infrared Spectrometers","TAFTS","Imperial College London"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Hyperspectral Spectrometers/Radiometers","Airborne Hyperspectral Scanner","Argon ST"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Hyperspectral Spectrometers/Radiometers","AisaDUAL","SPECIM"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Hyperspectral Spectrometers/Radiometers","AisaEAGLE 1K","SPECIM"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Hyperspectral Spectrometers/Radiometers","AisaEAGLE","SPECIM"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Hyperspectral Spectrometers/Radiometers","AisaFENIX 1K","SPECIM"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Hyperspectral Spectrometers/Radiometers","AisaFENIX","SPECIM"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Hyperspectral Spectrometers/Radiometers","AisaOWL","SPECIM"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Hyperspectral Spectrometers/Radiometers","CASI","ITRES Research Ltd"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Hyperspectral Spectrometers/Radiometers","CASI-1500i","ITRES Research Ltd"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Hyperspectral Spectrometers/Radiometers","CASI-550","ITRES Research Ltd"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Hyperspectral Spectrometers/Radiometers","HySpecScan","Analytical Spectral Devices Inc."],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Hyperspectral Spectrometers/Radiometers","IR/UV Line Scanner","OPTIMARE Systems GmbH"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Hyperspectral Spectrometers/Radiometers","PELICAN","IGN"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Imaging Spectrometers/Radiometers","Airborne Prism EXperiment","ESA"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Imaging Spectrometers/Radiometers","Airborne Thematic Mapper","DLR"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Imaging Spectrometers/Radiometers","Polifemo M21","SUPERELECTRIC s.r.l."],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Imaging Spectrometers/Radiometers","TASI-600","ITRES Research Ltd"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Imaging Spectrometers/Radiometers","TS9260","NEC Corporation"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Imaging Spectrometers/Radiometers","VIS Line Scanner","OPTIMARE Systems GmbH"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Infrared Radiometers","Everest 4000.4ZL","Everest Interscience Inc."],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Lidar/Laser Spectrometers","2D-C","Particle Measuring Systems"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Lidar/Laser Spectrometers","2D-P","Particle Measuring Systems"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Lidar/Laser Spectrometers","2D-S","Stratton Park Engineering Company"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Lidar/Laser Spectrometers","2D2C","Particle Measuring Systems"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Lidar/Laser Spectrometers","2DGB2","Particle Measuring Systems"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Lidar/Laser Spectrometers","ALS-450","Leosphere"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Lidar/Laser Spectrometers","ERS microjoule Lidar EMB-ER 1/2","ERS"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Lidar/Laser Spectrometers","OAP-200X","Particle Measuring Systems"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Lidar/Laser Spectrometers","OAP-230X","Particle Measuring Systems"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Lidar/Laser Spectrometers","OAP-230Y","Particle Measuring Systems"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Lidar/Laser Spectrometers","Ozone Lidar EXperiment","DLR"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Lidar/Laser Spectrometers","Portable Lidar System","University of Munich"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Lidar/Laser Spectrometers","RALI","LATMOS"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Lidar/Laser Spectrometers","WIND","DLR / CNRS / INSU"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Microwave Radiometers","DEIMOS","Met Office"], # Livre Jean Louis
	["Remote Sensing Instruments","Spectrometers/Radiometers","Microwave Radiometers","MARSS","Met Office"], # Livre Jean Louis
	["Remote Sensing Instruments","Spectrometers/Radiometers","Spectrometers","FUBISS","Free University of Berlin"], # A AFINER
	["Remote Sensing Instruments","Spectrometers/Radiometers","Spectrometers","FUBISS-ASA2","Free University Berlin"], # A AFINER
	["Remote Sensing Instruments","Spectrometers/Radiometers","Spectrometers","PRT 6","Barnes"], # A AFINER
	["Remote Sensing Instruments","Spectrometers/Radiometers","Spectrometers","SWS","Met Office"], # A AFINER
	["Remote Sensing Instruments","Spectrometers/Radiometers","Spectrometers","TABI320","ITRES Research Ltd"], # A AFINER
	["Remote Sensing Instruments","Spectrometers/Radiometers","Spectrometers","VIS/NIR Spectrometer ","Skye"], # A AFINER
	["Remote Sensing Instruments","Spectrometers/Radiometers","Spectrometers","VIS/NIR Spectrometer","Interspect Ltd."], # A AFINER
	["Remote Sensing Instruments","Spectrometers/Radiometers","Spectrometers","VIS/NIR Spectrometer","OceanOptics"], # A AFINER
	["Remote Sensing Instruments","Spectrometers/Radiometers","Spectroradiometers","4PI-SR","METEO-CONSULT"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Ultraviolet Spectrometers","GASCOD-A","FISBAT-CNR"],
	["Remote Sensing Instruments","Thermal/Radiation Detectors","Pyranometers","CMP-22","Kipp & Zonen"],
	["Remote Sensing Instruments","Thermal/Radiation Detectors","Pyranometers","Eppley PS Pyranometer","The Eppley Laboratory Inc."],
	["Remote Sensing Instruments","Thermal/Radiation Detectors","Pyranometers","LI-COR Pyranometer","LI-COR"],
	["Remote Sensing Instruments","Thermal/Radiation Detectors","Pyranometers","Walz UV Pyranometer","Heinz Walz Company"],
	["Remote Sensing Instruments","Thermal/Radiation Detectors","Pyrgeometers","CGR-4","Kipp & Zonen"],
	["Remote Sensing Instruments","Thermal/Radiation Detectors","Pyrgeometers","Eppley Pyrgeometer","The Eppley Laboratory Inc."],
	["Remote Sensing Instruments","Thermal/Radiation Detectors","Pyrometers","KT-15","Heitronics Infrarot Messtechnik"],
	]


instruments_classification = [
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Aerosol Monitors"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Aethalometers"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Air Permeameters"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","CHN Analyzers"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","CO2 Analyzers"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Carbon Analyzers"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Carbon, Hydrogen, Nitrogen Analyzers"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Condensation Nuclei Counter"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Fluorometers"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Gas Sensors"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Gaz Chromatographs"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Gaz Correlation Filters"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Infrared Gas Analyzer"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Ion Chromatographs"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Liquid Chromatographs"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Neutron Monitors"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Nondispersive Infrared Gas Analyzers"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Oxygen Analyzers"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Ozone Monitors"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","Porometers"],
	["In Situ/Laboratory Instruments","Chemical Meters/Analyzers","pH Meters"],
	["In Situ/Laboratory Instruments","Conductivity Sensors","Conductivity Meters"],
	["In Situ/Laboratory Instruments","Current/Wind Meters","Counterflow Virtual Impactors"],
	["In Situ/Laboratory Instruments","Current/Wind Meters","Wind Monitors"],
	["In Situ/Laboratory Instruments","Magnetic/Motion Sensors","Accelerographs"],
	["In Situ/Laboratory Instruments","Magnetic/Motion Sensors","Accelerometers"],
	["In Situ/Laboratory Instruments","Magnetic/Motion Sensors","Gravimeters"],
	["In Situ/Laboratory Instruments","Magnetic/Motion Sensors","Inclinometers"],
	["In Situ/Laboratory Instruments","Photon/Optical Detectors ","Tunable Diode Lasers"],
	["In Situ/Laboratory Instruments","Photon/Optical Detectors","Binoculars"],
	["In Situ/Laboratory Instruments","Photon/Optical Detectors","Cameras"],
	["In Situ/Laboratory Instruments","Photon/Optical Detectors","Optical Particle Counters"],  # Livre Jean Louis
	["In Situ/Laboratory Instruments","Photon/Optical Detectors","Turbidity Meters"],
	["In Situ/Laboratory Instruments","Photon/Optical Detectors","Visual Observations"],
	["In Situ/Laboratory Instruments","Pressure/Height Meters","Barometers"],
	["In Situ/Laboratory Instruments","Pressure/Height Meters","Microbarographs"],
	["In Situ/Laboratory Instruments","Pressure/Height Meters","Pitot-static System"],
	["In Situ/Laboratory Instruments","Pressure/Height Meters","Pressure Sensors"],
	["In Situ/Laboratory Instruments","Probes","Cloud Droplet Probes"],
	["In Situ/Laboratory Instruments","Probes","Cloud Liquid Water Probes"],
	["In Situ/Laboratory Instruments","Probes","Dielectric Probes"],
	["In Situ/Laboratory Instruments","Probes","Neutron Probes"],
	["In Situ/Laboratory Instruments","Probes","Nevzorov Probes"],
	["In Situ/Laboratory Instruments","Probes","Probes"],
	["In Situ/Laboratory Instruments","Probes","Temperature Probes"],
	["In Situ/Laboratory Instruments","Radiation Sensors","Quantum Sensors"],
	["In Situ/Laboratory Instruments","Samplers","Bottles / Flasks / Jars"],
	["In Situ/Laboratory Instruments","Samplers","Grabbers /Traps / Collectors"],
	["In Situ/Laboratory Instruments","Spectrometers/Radiometers","Chemiluminescence"],
	["In Situ/Laboratory Instruments","Spectrometers/Radiometers","Colorimeters"],
	["In Situ/Laboratory Instruments","Spectrometers/Radiometers","Mass Spectrometers"],
	["In Situ/Laboratory Instruments","Spectrometers/Radiometers","Net Radiometers"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Humidity Sensors"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Humidity Transducers"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Hydrometers"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Hygrometers"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Hypsometers"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Psychrometers"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Soil Heat Flux Transducers"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Temperature Sensors"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Thermistors"],
	["In Situ/Laboratory Instruments","Temperature/Humidity Sensors","Thermometers"],
	["Remote Sensing Instruments","Altimeters","Lidar/Laser Altimeters"],
	["Remote Sensing Instruments","Altimeters","Radar Altimeters"],
	["Remote Sensing Instruments","Imaging Radars","Active Microwave Instruments"],
	["Remote Sensing Instruments","Imaging Radars","Advanced SAR"],
	["Remote Sensing Instruments","Imaging Radars","Airborn SAR"],
	["Remote Sensing Instruments","Imaging Radars","C-Band SAR"],
	["Remote Sensing Instruments","Imaging Radars","Phased Array type L-band SAR"],
	["Remote Sensing Instruments","Imaging Radars","SAR"],
	["Remote Sensing Instruments","Imaging Radars","Side-Looking Airborne Radars"],
	["Remote Sensing Instruments","Imaging Radars","Water Content Reflectometers"],
	["Remote Sensing Instruments","Imaging Radars","X-Band SAR"],
	["Remote Sensing Instruments","Magnetic/Electric Field Instruments","Magnetic Variometers"],
	["Remote Sensing Instruments","Magnetic/Electric Field Instruments","Magnetometers"],
	["Remote Sensing Instruments","Magnetic/Electric Field Instruments","Nuclear Precession Magnetometers"],
	["Remote Sensing Instruments","Magnetic/Electric Field Instruments","Overhauser Scalar Magnetometers"],
	["Remote Sensing Instruments","Magnetic/Electric Field Instruments","Proton Magnetometers"],
	["Remote Sensing Instruments","Magnetic/Motion Sensors","Accelerometers"],
	["Remote Sensing Instruments","Magnetic/Motion Sensors","Gravimeters"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Cameras"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Ceilometers"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Gas Filter Correlated Radiometer"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Monochromators"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Nephelometers"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Particle Detectors"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Photoelectric Aerosol Sensor"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Photometers"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Polarimeters"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Scintillation Counters"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Sunshine Recorders"],
	["Remote Sensing Instruments","Photon/Optical Detectors","Video Cameras"],
	["Remote Sensing Instruments","Positioning/Navigation","Compasses"],
	["Remote Sensing Instruments","Positioning/Navigation","Ground Positioning Systems"],
	["Remote Sensing Instruments","Positioning/Navigation","Gyros"],
	["Remote Sensing Instruments","Positioning/Navigation","RF Antennas"],
	["Remote Sensing Instruments","Positioning/Navigation","Radars"],
	["Remote Sensing Instruments","Positioning/Navigation","Transponders"],
	["Remote Sensing Instruments","Positioning/Navigation","VLF Receivers"],
	["Remote Sensing Instruments","Scatterometers","Advance Scatterometers"],
	["Remote Sensing Instruments","Scatterometers","Aquarius Scatterometers"],
	["Remote Sensing Instruments","Scatterometers","SEASAT-A Scatterometer"],
	["Remote Sensing Instruments","Scatterometers","Scatterometers"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Cloud, Aerosol, Precipitation Spectrometers"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Fourier Transform Infrared Spectrometers"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Hyperspectral Spectrometers / Radiometer"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Imaging Spectrometers/Radiometers"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Infrared Radiometers"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Interferometers"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Lidar/Laser Spectrometers"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Microwave Radiometers"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Radiometers"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Spectrometers"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Spectroradiometers"],
	["Remote Sensing Instruments","Spectrometers/Radiometers","Ultraviolet Spectrometers"],
	["Remote Sensing Instruments","Thermal/Radiation Detectors","Actinometers"],
	["Remote Sensing Instruments","Thermal/Radiation Detectors","Bolometers"],
	["Remote Sensing Instruments","Thermal/Radiation Detectors","Pygeometers"],
	["Remote Sensing Instruments","Thermal/Radiation Detectors","Pyranometers"],
	["Remote Sensing Instruments","Thermal/Radiation Detectors","Pyrheliometers"],
	["Remote Sensing Instruments","Thermal/Radiation Detectors","Pyrometers"],
	["Remote Sensing Instruments","Thermal/Radiation Detectors","Pyrradiometers"],
	["Remote Sensing Instruments","Thermal/Radiation Detectors","Solarimeters"],
	]


elements_informations = [
	["5","cl_label_1","Topic Category","Classification",""],
	["6","kw_category_lb1","Keywords","Keywords",""],
	["1","id_resourceTitle_ln","Resource title","Identification","text"],
	["2","id_resourceAbstract_ta","Resource abstract","Identification","text"],
	["3","id_resourceLocator_ln","Resource locator","Identification","text"],
	["4","id_resourceIdent_ln","Unique resource identifier","Identification","text"],
	#["6","kw_name_ln","Name","Keyword",""],
	#["7","kw_keyword_ls","Keywords","Keyword",""],
	["8","ai_label_1","Aircraft","Aircraft and Instruments",""],
	["9","ai_label_13","Instrument 1","Aircraft and Instruments",""],
	["10","gl_location_lb","Location","Geographic Information",""],
	["11","gl_northBound_ln","Geographic bounding box - North","Geographic Information","float"],
	["12","gl_southBound_ln","Geographic bounding box - South","Geographic Information","float"],
	["13","gl_eastBound_ln","Geographic bounding box - East","Geographic Information","float"],
	["14","gl_westBound_ln","Geographic bounding box - West","Geographic Information","float"],
	["15","gl_resolution_ln","Spatial Resolution","Geographic Information","float"],
	["16","gl_unit_ln","Spatial Resolution - Unit","Geographic Information","text"],
	["17","qv_lineage_ta","Lineage","Quality and Validity","text"],
	#["10","gl_name_ln","Coordinate Reference System - Name","Geographic Information",""],
	#["11","gl_code_ln","Coordinate Reference System - Code","Geographic Information",""],
	#["12","gl_northBound_ln","Geographic bounding box - North","Geographic Information",""],
	#["13","gl_southBound_ln","Geographic bounding box - South","Geographic Information",""],
	#["14","gl_eastBound_ln","Geographic bounding box - East","Geographic Information",""],
	#["15","gl_westBound_ln","Geographic bounding box - West","Geographic Information",""],
	#["16","gl_continent_ln","Continent / Country / Region","Geographic Information",""],
	#["17","qv_lineage_ta","Lineage","Quality and Validity",""],
	#["18","qv_resolution_ln","Spatial Resolution","Quality and Validity",""],
	#["19","qv_unit_ln","Spatial Resolution - Unit","Quality and Validity",""],
	#["20","cf_specification_ln","Specification","Conformity",""],
	["21","au_conditions_ta","Conditions applying to access and use","Access and Use Constraints","text"],
	["22","au_limitations_ta","Limitations on public access","Access and Use Constraints","text"],
	["23","au_wn_con_ta","Conditions applying to access and use","Access and Use Constraints","text"],
	["24","au_wn_lim_ta","Limitations on public access","Access and Use Constraints","text"],
	["25","ro_responsibleParty_ln","Responsible party","Responsible Organisations","text"],
	["26","ro_responsibleEmail_ln","Responsible party e-mail","Responsible Organisations","text"],
	["27","ro_rlPy_ln","Responsible party","Responsible Organisations","text"],
	["28","ro_rlEm_ln","Responsible party e-mail","Responsible Organisations","text"],
	["29","mm_contactName_ln","Name","Metadata on Metadata","text"],
	["30","mm_contactEmail_ln","E-mail","Metadata on Metadata","text"],
	["31","mm_conName_ln","Name","Metadata on Metadata","text"],
	["32","mm_conEmail_ln","E-mail","Metadata on Metadata","text"],
	
	
	]

path = os.getcwd()

if path == "/home/henryo/Travail/python/EUFAR_metadata_creator":
  path += "/sqlite"

con = lite.connect(path + "/emc_database.db")


with con:
    
    cur = con.cursor()    
    cur.execute("DROP TABLE IF EXISTS aircraftInformations")
    cur.execute("CREATE TABLE aircraftInformations(Id TEXT, Manufacturer TEXT, Type TEXT, Operator TEXT, Country TEXT, Code TEXT, Image TEXT, Copyright TEXT)")
    cur.executemany("INSERT INTO aircraftInformations VALUES(?, ?, ?, ?, ?, ?, ?, ?)", aircraft_informations)
    
    cur = con.cursor()    
    cur.execute("DROP TABLE IF EXISTS languageRole")
    cur.execute("CREATE TABLE languageRole(Id TEXT, Short TEXT)")
    cur.executemany("INSERT INTO languageRole VALUES(?, ?)", language_role_dict)
    
    cur = con.cursor()    
    cur.execute("DROP TABLE IF EXISTS windowsMessage")
    cur.execute("CREATE TABLE windowsMessage(Button TEXT, Message TEXT)")
    cur.executemany("INSERT INTO windowsMessage VALUES(?, ?)", window_messages)
    
    cur = con.cursor()    
    cur.execute("DROP TABLE IF EXISTS instrumentsInformations")
    cur.execute("CREATE TABLE instrumentsInformations(Domain TEXT, Category TEXT, Type TEXT, Model TEXT, Manufacturer TEXT)")
    cur.executemany("INSERT INTO instrumentsInformations VALUES(?, ?, ?, ?, ?)", intruments_information)
    
    cur = con.cursor()    
    cur.execute("DROP TABLE IF EXISTS topics")
    cur.execute("CREATE TABLE topics(Text TEXT, Value TEXT)")
    cur.executemany("INSERT INTO topics VALUES(?, ?)", topic_dict)
    
    cur = con.cursor()    
    cur.execute("DROP TABLE IF EXISTS instrumentsClassification")
    cur.execute("CREATE TABLE instrumentsClassification(Domain TEXT, Category TEXT, Type TEXT)")
    cur.executemany("INSERT INTO instrumentsClassification VALUES(?, ?, ?)", instruments_classification)
    
    cur = con.cursor()    
    cur.execute("DROP TABLE IF EXISTS elementsInformation")
    cur.execute("CREATE TABLE elementsInformation(Place INT, Object TEXT, Name TEXT, Page TEXT, Type TEXT)")
    cur.executemany("INSERT INTO elementsInformation VALUES(?, ?, ?, ?, ?)", elements_informations)
    
    cur = con.cursor()    
    cur.execute("DROP TABLE IF EXISTS emcLocations")
    cur.execute("CREATE TABLE emcLocations(Category TEXT, Detail TEXT)")
    cur.executemany("INSERT INTO emcLocations VALUES(?, ?)", emc_locations)
    
    cur = con.cursor()    
    cur.execute("DROP TABLE IF EXISTS scienceKeywords")
    cur.execute("CREATE TABLE scienceKeywords(Category TEXT, Keywords TEXT, Labels TEXT)")
    cur.executemany("INSERT INTO scienceKeywords VALUES(?, ?, ?)", ceos_science_keywords)
 
    
con.close()