# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'infowindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_infoWindow(object):
    def setupUi(self, infoWindow):
        infoWindow.setObjectName("infoWindow")
        infoWindow.resize(450, 180)
        infoWindow.setMinimumSize(QtCore.QSize(450, 180))
        infoWindow.setMaximumSize(QtCore.QSize(452, 16777215))
        font = QtGui.QFont()
        font.setFamily("font/SourceSansPro-Regular.ttf")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        infoWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/info_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        infoWindow.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(infoWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.iw_label_2 = QtWidgets.QLabel(infoWindow)
        self.iw_label_2.setMinimumSize(QtCore.QSize(55, 55))
        self.iw_label_2.setMaximumSize(QtCore.QSize(55, 55))
        self.iw_label_2.setText("")
        self.iw_label_2.setPixmap(QtGui.QPixmap("icons/info_icon.png"))
        self.iw_label_2.setScaledContents(True)
        self.iw_label_2.setObjectName("iw_label_2")
        self.verticalLayout.addWidget(self.iw_label_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.iw_label_1 = QtWidgets.QLabel(infoWindow)
        self.iw_label_1.setMinimumSize(QtCore.QSize(341, 120))
        self.iw_label_1.setMaximumSize(QtCore.QSize(341, 16777215))
        font = QtGui.QFont()
        font.setFamily("font/SourceSansPro-Regular.ttf")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.iw_label_1.setFont(font)
        self.iw_label_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.iw_label_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.iw_label_1.setLineWidth(0)
        self.iw_label_1.setMidLineWidth(0)
        self.iw_label_1.setText("")
        self.iw_label_1.setTextFormat(QtCore.Qt.AutoText)
        self.iw_label_1.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.iw_label_1.setWordWrap(True)
        self.iw_label_1.setObjectName("iw_label_1")
        self.horizontalLayout.addWidget(self.iw_label_1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.iw_okButton = QtWidgets.QPushButton(infoWindow)
        self.iw_okButton.setMinimumSize(QtCore.QSize(50, 27))
        self.iw_okButton.setMaximumSize(QtCore.QSize(50, 27))
        font = QtGui.QFont()
        font.setFamily("font/SourceSansPro-Regular.ttf")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.iw_okButton.setFont(font)
        self.iw_okButton.setObjectName("iw_okButton")
        self.horizontalLayout_2.addWidget(self.iw_okButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(infoWindow)
        QtCore.QMetaObject.connectSlotsByName(infoWindow)

    def retranslateUi(self, infoWindow):
        _translate = QtCore.QCoreApplication.translate
        infoWindow.setWindowTitle(_translate("infoWindow", "Information"))
        self.iw_okButton.setText(_translate("infoWindow", "OK"))

